import {createServer} from 'node:http';
import {randomBytes,createHash} from 'node:crypto';
import {createRemoteJWKSet,jwtVerify} from 'jose';
export interface IdentityConfig {clientId:string;issuer:string;redirectUri:string;}
export function pkce(){const verifier=randomBytes(32).toString('base64url');return{verifier,challenge:createHash('sha256').update(verifier).digest('base64url')};}
export async function chatgptSignIn(config:IdentityConfig,open:(url:string)=>Promise<void>){
 const issuer=new URL(config.issuer);if(issuer.protocol!=='https:')throw Error('OAuth issuer must use HTTPS');const callback=new URL(config.redirectUri);if(callback.hostname!=='127.0.0.1'||callback.protocol!=='http:')throw Error('Use a registered loopback callback on 127.0.0.1');
 const discovery:any=await fetch(new URL(issuer.href.replace(/\/$/,'')+'/.well-known/openid-configuration'),{redirect:'error'}).then(r=>{if(!r.ok)throw Error('OAuth discovery unavailable');return r.json();});if(discovery.issuer!==config.issuer)throw Error('OAuth issuer mismatch');for(const endpoint of [discovery.authorization_endpoint,discovery.token_endpoint,discovery.jwks_uri])if(new URL(endpoint).protocol!=='https:')throw Error('OAuth endpoints must use HTTPS');
 const {verifier,challenge}=pkce(),state=randomBytes(32).toString('base64url'),nonce=randomBytes(32).toString('base64url');
 let timer:ReturnType<typeof setTimeout>;
 const code=await new Promise<string>((ok,no)=>{
  const server=createServer((req,res)=>{const url=new URL(req.url??'/',callback.origin);if(url.pathname!==callback.pathname){res.writeHead(404).end();return;}if(url.searchParams.get('state')!==state){res.writeHead(400).end('Invalid sign-in state');return;}clearTimeout(timer);server.close();if(url.searchParams.has('error')){res.writeHead(400).end('Sign-in cancelled. Return to Fox Bot.');no(Error('Sign-in cancelled'));return;}const value=url.searchParams.get('code');if(!value){res.writeHead(400).end('Missing authorization code');no(Error('Missing code'));return;}res.setHeader('Content-Type','text/plain; charset=utf-8');res.end('Sign-in received. Return to Fox Bot.');ok(value);});
  server.on('error',no);server.listen(Number(callback.port),callback.hostname,()=>{const url=new URL(discovery.authorization_endpoint);url.search=new URLSearchParams({client_id:config.clientId,redirect_uri:config.redirectUri,response_type:'code',scope:'openid profile email',state,nonce,code_challenge:challenge,code_challenge_method:'S256'}).toString();void open(url.href).catch(e=>{server.close();clearTimeout(timer);no(e);});});timer=setTimeout(()=>{server.close();no(Error('Sign-in timed out'));},300000);
 });
 const response=await fetch(discovery.token_endpoint,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'authorization_code',client_id:config.clientId,redirect_uri:config.redirectUri,code,code_verifier:verifier}),redirect:'error'});if(!response.ok)throw Error('OAuth token exchange failed');const token:any=await response.json();if(typeof token.id_token!=='string')throw Error('Identity token missing');const {payload}=await jwtVerify(token.id_token,createRemoteJWKSet(new URL(discovery.jwks_uri)),{issuer:config.issuer,audience:config.clientId,requiredClaims:['sub','exp','iat']});if(payload.nonce!==nonce)throw Error('OAuth nonce mismatch');return{subject:payload.sub,issuer:payload.iss,name:payload.name,email:payload.email,verifiedAt:new Date().toISOString()};
}
export async function openrouterConnect(open:(url:string)=>Promise<void>){const {verifier,challenge}=pkce();let timer:ReturnType<typeof setTimeout>;let url:string;
 const code=await new Promise<string>((ok,no)=>{const server=createServer((req,res)=>{const u=new URL(req.url??'/',url);if(u.pathname!=='/callback'){res.writeHead(404).end();return;}const c=u.searchParams.get('code');if(!c){res.writeHead(400).end('Missing authorization code');return;}clearTimeout(timer);server.close();res.end('Return to Fox Bot.');ok(c);});server.on('error',no);server.listen(0,'127.0.0.1',()=>{url=`http://127.0.0.1:${(server.address() as any).port}/callback`;const auth=new URL('https://openrouter.ai/auth');auth.search=new URLSearchParams({callback_url:url,code_challenge:challenge,code_challenge_method:'S256'}).toString();void open(auth.href).catch(e=>{clearTimeout(timer);server.close();no(e);});});timer=setTimeout(()=>{server.close();no(Error('OpenRouter connection timed out'));},300000);});
 const r=await fetch('https://openrouter.ai/api/v1/auth/keys',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code,code_verifier:verifier,code_challenge_method:'S256'}),redirect:'error'});if(!r.ok)throw Error('OpenRouter connection failed');const data:any=await r.json();if(typeof data.key!=='string')throw Error('No API key returned');return data.key;
}
