import {app,BrowserWindow,ipcMain,utilityProcess,shell,dialog,nativeImage,Tray,Menu,session,desktopCapturer,screen} from 'electron';
import {randomUUID} from 'node:crypto';
import {mkdirSync,readFileSync,writeFileSync,existsSync} from 'node:fs';
import {join,resolve,basename} from 'node:path';
import {pathToFileURL} from 'node:url';
import QRCode from 'qrcode';
import {Vault} from './vault';
import {chatgptSignIn,openrouterConnect} from './auth';
import {NativeHelper} from './native';
import {HostRelay} from './relay';
import {SpeechAdapter,SPEECH_LIMITS,speechCapabilities,type SpeechProfile} from '../runtime/speech';
import {connectorManifestSchema} from '../runtime/connectors';
import {z} from 'zod';
import type {CommandResult} from '@foxbot/protocol';
let win:BrowserWindow,background:BrowserWindow,tray:Tray,worker:ReturnType<typeof utilityProcess.fork>,vault:Vault,native:NativeHelper,relay:HostRelay|undefined;let quitting=false;
const waiting=new Map<string,{resolve:(r:CommandResult)=>void,reject:(e:Error)=>void}>();let ready:Promise<void>;let readyResolve:()=>void;
const speechRequests=new Map<string,AbortController>();
const compatibleSpeech=z.object({transcription:z.boolean(),synthesis:z.boolean(),inputFormats:z.array(z.enum(['webm','wav','ogg','mp3','mp4','mpeg','mpga','m4a','flac'])),outputFormats:z.array(z.enum(['mp3','wav','opus','aac','flac','pcm','mulaw','alaw']))}).strict();
const speechBase={requestId:z.string().uuid(),providerId:z.string().uuid(),model:z.string().trim().min(1).max(200).optional(),compatibleCapabilities:compatibleSpeech.optional()};
const transcriptionRequest=z.object({...speechBase,base64:z.string().min(1).max(Math.ceil(SPEECH_LIMITS.inputBytes/3)*4).refine(s=>s.length%4===0&&/^[A-Za-z0-9+/]*={0,2}$/.test(s),'Invalid base64 audio'),filename:z.string().max(160),mime:z.string().max(100),language:z.string().max(50).optional()}).strict();
const synthesisRequest=z.object({...speechBase,text:z.string().min(1).max(SPEECH_LIMITS.textCharacters),voice:z.string().max(100).optional(),format:z.enum(['mp3','wav','opus','aac','flac','pcm','mulaw','alaw']).optional(),language:z.string().max(50).optional()}).strict();
async function selectedSpeech(providerId:string,capabilities?:z.infer<typeof compatibleSpeech>):Promise<SpeechProfile>{const state=await command('snapshot',{});if(!state.ok)throw Error('Cannot read connected speech providers');const provider=(state.data as any).providers.find((p:any)=>p.id===providerId);if(!provider)throw Error('Speech provider is not connected');if(!['openai','xai','compatible'].includes(provider.kind))throw Error('This provider has no implemented speech adapter');if(provider.kind==='compatible'&&!capabilities)throw Error('Confirm your compatible endpoint supports the selected audio capabilities');return{id:provider.id,kind:provider.kind,baseUrl:provider.baseUrl,auth:provider.hasCredential?'bearer':provider.kind==='compatible'?'none':'bearer',...(provider.kind==='compatible'?{capabilities}:{} )};}
function cancelSpeech(){for(const controller of speechRequests.values())controller.abort();speechRequests.clear();}
const dir=()=>app.getPath('userData');
function broadcast(event:any){if(win&&!win.isDestroyed())win.webContents.send('fox:event',event);if(background&&!background.isDestroyed())background.webContents.send('fox:event',event);}
async function command(type:string,payload:any,commandId=randomUUID()):Promise<CommandResult>{await ready;const requestId=randomUUID();return new Promise((resolve,reject)=>{waiting.set(requestId,{resolve,reject});worker.postMessage({type:'command',requestId,command:{version:1,id:commandId,type,payload}});});}
const rendererUrl=pathToFileURL(join(__dirname,'renderer/index.html')).href;
function trust(event:Electron.IpcMainInvokeEvent,remote=false){if(event.sender!==win.webContents && !(remote&&event.sender===background.webContents))throw Error('Untrusted IPC sender');if(event.senderFrame!==event.sender.mainFrame||event.senderFrame.url.split('#')[0]!==rendererUrl)throw Error('Untrusted frame');}
function getRelay(){if(!relay)relay=new HostRelay(dir(),vault,m=>win.webContents.send('fox:remote',m),m=>background.webContents.send('fox:remote',m));return relay;}
function protect(w:BrowserWindow){w.webContents.setWindowOpenHandler(({url})=>{if(/^https?:/.test(url))void shell.openExternal(url);return{action:'deny'};});w.webContents.on('will-navigate',(e,url)=>{if(url.split('#')[0]!==rendererUrl)e.preventDefault();});}
async function nativeRequest(method:string,args:any){if(method==='input'){const display=screen.getPrimaryDisplay();if(args.kind==='click'){const dip={x:Math.round(display.bounds.x+args.x*display.bounds.width),y:Math.round(display.bounds.y+args.y*display.bounds.height)};const point=process.platform==='win32'?screen.dipToScreenPoint(dip):dip;return native.call('click',point);}if(args.kind==='text')return native.call('type',{text:args.text});if(args.kind==='key')return native.call('key',{key:args.key});if(args.kind==='scroll')return native.call('scroll',{amount:args.amount});throw Error('Invalid input');}return native.call(method,args);}
app.whenReady().then(async()=>{
 mkdirSync(dir(),{recursive:true});vault=new Vault(dir());native=new NativeHelper(app.isPackaged?join(process.resourcesPath,'native'):resolve(__dirname,'../../../native/target/release'));
 const browserDirectory=app.isPackaged?join(process.resourcesPath,'browsers'):resolve(__dirname,'../../../vendor/browsers');
 ready=new Promise(r=>readyResolve=r);worker=utilityProcess.fork(join(__dirname,'worker.cjs'),[dir()],{serviceName:'Fox Bot runtime',env:{...process.env,PLAYWRIGHT_BROWSERS_PATH:browserDirectory}});
 worker.on('message',async(m:any)=>{if(m.type==='ready'){readyResolve();return;}if(m.type==='result'){waiting.get(m.requestId)?.resolve(m.result);waiting.delete(m.requestId);}if(m.type==='event')broadcast(m.event);if(m.type==='credential'||m.type==='connector.credential'||m.type==='native'){try{const data=m.type==='credential'?vault.get('provider:'+m.data.id):m.type==='connector.credential'?vault.get('connector:'+m.data.id):await nativeRequest(m.data.method,m.data.args);worker.postMessage({type:'host.result',id:m.id,data});}catch(e:any){worker.postMessage({type:'host.result',id:m.id,error:e.message});}}});
 worker.on('exit',()=>{for(const p of waiting.values())p.reject(Error('Fox Bot runtime stopped'));waiting.clear();broadcast({type:'runtime.stopped'});});
 win=new BrowserWindow({width:1250,height:860,minWidth:800,minHeight:600,title:'Fox Bot',backgroundColor:'#080808',autoHideMenuBar:true,webPreferences:{preload:join(__dirname,'preload.cjs'),nodeIntegration:false,contextIsolation:true,sandbox:true}});protect(win);
 background=new BrowserWindow({show:false,width:1,height:1,webPreferences:{preload:join(__dirname,'preload.cjs'),nodeIntegration:false,contextIsolation:true,sandbox:true,backgroundThrottling:false}});protect(background);
 let microphoneGranted=false;
 session.defaultSession.setPermissionCheckHandler((contents,permission,_origin,details)=>{if(permission==='display-capture')return contents===background.webContents;return contents===win.webContents&&permission==='media'&&details.mediaType==='audio'&&microphoneGranted;});
 session.defaultSession.setPermissionRequestHandler((contents,permission,callback,details)=>{if(contents===background.webContents&&permission==='display-capture'){callback(true);return;}if(contents!==win.webContents||permission!=='media'||!contents.getURL().startsWith('file:')||!('mediaTypes'in details)||!details.mediaTypes?.length||details.mediaTypes.some(t=>t!=='audio')){callback(false);return;}void dialog.showMessageBox(win,{type:'question',title:'Microphone access',message:'Allow Fox Bot to record your microphone?',detail:'Recording stays in this window until you choose Transcribe. The selected speech provider receives the recording only after that action.',buttons:['Allow microphone','Cancel'],defaultId:1,cancelId:1}).then(result=>{microphoneGranted=result.response===0;callback(microphoneGranted);}).catch(()=>callback(false));});
 session.defaultSession.setDisplayMediaRequestHandler(async(request,callback)=>{if(request.frame!==background.webContents.mainFrame){callback({});return;}const sources=await desktopCapturer.getSources({types:['screen']});const primary=String(screen.getPrimaryDisplay().id);callback({video:sources.find(s=>s.display_id===primary)??sources[0]});});
 const icon=nativeImage.createFromDataURL('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+j1ioAAAAASUVORK5CYII=').resize({width:16,height:16});tray=new Tray(icon);tray.setToolTip('Fox Bot — local runtime');tray.setContextMenu(Menu.buildFromTemplate([{label:'Open Fox Bot',click:()=>win.show()},{label:'Emergency stop',click:()=>void command('emergency.stop',{})},{label:'Quit Fox Bot',click:()=>{quitting=true;app.quit();}}]));tray.on('click',()=>win.show());win.on('close',e=>{if(!quitting){e.preventDefault();win.hide();}});
 ipcMain.handle('fox:command',(event,{type,payload})=>{trust(event);return command(type,payload);});
 ipcMain.handle('fox:desktop',async(event,{type,payload})=>{trust(event);try{
  if(type.startsWith('speech.')&&event.senderFrame!==win.webContents.mainFrame)throw Error('Speech operations require the trusted desktop frame');
  if(type==='status'){const identityFile=join(dir(),'identity.json');return{ok:true,data:{secureStorage:vault.available(),identity:existsSync(identityFile)?JSON.parse(readFileSync(identityFile,'utf8')):null,chatgptAvailable:!!(process.env.FOX_CHATGPT_CLIENT_ID&&process.env.FOX_CHATGPT_ISSUER),version:app.getVersion(),workspace:join(dir(),'workspace'),remote:relay?.status()??null}};}
  if(type==='auth.chatgpt'){if(!process.env.FOX_CHATGPT_CLIENT_ID||!process.env.FOX_CHATGPT_ISSUER)throw Error('Official ChatGPT client registration is required. Configure FOX_CHATGPT_CLIENT_ID and FOX_CHATGPT_ISSUER.');const identity=await chatgptSignIn({clientId:process.env.FOX_CHATGPT_CLIENT_ID,issuer:process.env.FOX_CHATGPT_ISSUER,redirectUri:process.env.FOX_CHATGPT_REDIRECT_URI??'http://127.0.0.1:42173/callback'},url=>shell.openExternal(url));writeFileSync(join(dir(),'identity.json'),JSON.stringify(identity),{mode:0o600});return{ok:true,data:identity};}
  if(type==='provider.save'){const id=payload.id??randomUUID();if(payload.key)vault.set('provider:'+id,payload.key);const {key,...profile}=payload;return await command('provider.save',{...profile,id,hasCredential:!!vault.get('provider:'+id)});}
  if(type==='provider.openrouter'){const key=await openrouterConnect(url=>shell.openExternal(url));const id=randomUUID();vault.set('provider:'+id,key);return await command('provider.save',{id,kind:'openrouter',name:'OpenRouter',hasCredential:true});}
  if(type==='connector.save'){const manifest=connectorManifestSchema.parse(payload.manifest);const key=payload.key===undefined?undefined:z.string().max(10000).parse(payload.key);const previous=key===undefined?undefined:vault.get('connector:'+manifest.id);if(key!==undefined)vault.set('connector:'+manifest.id,key);try{const result=await command('connector.save',manifest);if(!result.ok&&key!==undefined)vault.set('connector:'+manifest.id,previous??'');return result;}catch(e){if(key!==undefined)vault.set('connector:'+manifest.id,previous??'');throw e;}}
  if(type==='connector.remove'){const id=z.string().min(1).max(40).parse(payload.id);const result=await command('connector.remove',{id});if(result.ok)vault.set('connector:'+id,'');return result;}
  if(type==='speech.cancel'){const requestId=z.string().uuid().parse(payload.requestId);speechRequests.get(requestId)?.abort();return{ok:true};}
  if(type==='speech.capabilities'){const providerId=z.string().uuid().parse(payload.providerId);const profile=await selectedSpeech(providerId,payload.compatibleCapabilities?compatibleSpeech.parse(payload.compatibleCapabilities):undefined);return{ok:true,data:speechCapabilities(profile)};}
  if(type==='speech.transcribe'||type==='speech.synthesize'){
   const request=type==='speech.transcribe'?transcriptionRequest.parse(payload):synthesisRequest.parse(payload);if(speechRequests.has(request.requestId))throw Error('Speech request ID is already active');if(speechRequests.size>=2)throw Error('At most two speech requests may run at once');const controller=new AbortController();speechRequests.set(request.requestId,controller);
   try{const profile=await selectedSpeech(request.providerId,request.compatibleCapabilities);controller.signal.throwIfAborted();const adapter=new SpeechAdapter({credential:async id=>vault.get('provider:'+id)});
    if(type==='speech.transcribe'){const input=transcriptionRequest.parse(payload);const bytes=Buffer.from(input.base64,'base64');if(bytes.length>SPEECH_LIMITS.inputBytes||bytes.toString('base64')!==input.base64)throw Error('Invalid bounded audio encoding');return{ok:true,data:await adapter.transcribe(profile,{bytes,filename:input.filename,mime:input.mime,model:input.model,language:input.language},controller.signal)};}
    const input=synthesisRequest.parse(payload);const result=await adapter.synthesize(profile,{text:input.text,model:input.model,voice:input.voice,format:input.format,language:input.language},controller.signal);return{ok:true,data:{base64:Buffer.from(result.bytes).toString('base64'),mime:result.mime,format:result.format}};
   }finally{speechRequests.delete(request.requestId);}
  }
  if(type==='attachment.pick'){const selection=await dialog.showOpenDialog(win,{properties:['openFile','multiSelections']});if(selection.canceled)return{ok:true,data:[]};const attachments=[];for(const path of selection.filePaths.slice(0,6)){const bytes=readFileSync(path);if(bytes.length>25*1024*1024)throw Error('Attachment exceeds 25 MB');const extension=path.split('.').at(-1)?.toLowerCase();const mime=({png:'image/png',jpg:'image/jpeg',jpeg:'image/jpeg',pdf:'application/pdf',txt:'text/plain',md:'text/markdown',csv:'text/csv'} as any)[extension??'']??'application/octet-stream';const result=await command('attachment.upload',{name:basename(path),mime,base64:bytes.toString('base64')});if(!result.ok)throw Error(result.error?.message);attachments.push(result.data);}return{ok:true,data:attachments};}
  if(type==='workspace.open'){await shell.openPath(join(dir(),'workspace'));return{ok:true};}
  if(type==='template.export'){const s:any=(await command('snapshot',{})).data;const b=s.bots.find((b:any)=>b.id===payload.id);if(!b)throw Error('Bot not found');const selection=await dialog.showSaveDialog(win,{defaultPath:b.name+'.foxbot.json'});if(selection.filePath){const {id,providerId,revision,createdAt,...publicBot}=b;writeFileSync(selection.filePath,JSON.stringify({version:1,bot:publicBot},null,2));}return{ok:true};}
  if(type==='template.import'){const selection=await dialog.showOpenDialog(win,{properties:['openFile'],filters:[{name:'Fox Bot template',extensions:['json']}]});if(selection.canceled)return{ok:true};const template=JSON.parse(readFileSync(selection.filePaths[0],'utf8'));if(template.version!==1)throw Error('Unsupported template');return command('bot.create',{...template.bot,providerId:''});}
  if(type==='artifact.open'){const result=await command('artifact.read',{id:payload.id});if(!result.ok)return result;const a:any=result.data;const selected=await dialog.showSaveDialog(win,{defaultPath:basename(a.name)});if(selected.filePath){writeFileSync(selected.filePath,Buffer.from(a.base64,'base64'));await shell.openPath(selected.filePath);}return{ok:true};}
  if(type==='remote.configure'){const r=getRelay();r.configure(payload.endpoint,payload.token);r.start();return{ok:true,data:r.status()};}
  if(type==='remote.status')return{ok:true,data:getRelay().status()};
  if(type==='remote.pairing'){const offer=getRelay().pairing();return{ok:true,data:{offer,qr:await QRCode.toDataURL(JSON.stringify(offer))}};}
  if(type==='remote.approve'){getRelay().approve(payload.peerId,payload.approved);return{ok:true};}
  if(type==='remote.revoke'){getRelay().revoke(payload.id);return{ok:true};}
  throw Error('Unknown desktop operation');
 }catch(e:any){return{ok:false,error:{message:e.message}};}});
 ipcMain.handle('fox:remote',async(event,{type,payload})=>{trust(event,true);if(event.sender!==background.webContents)throw Error('Remote bridge restricted to background');if(type==='signal'){getRelay().signal(payload);return;}if(type==='command'){const peer=getRelay().devices.find(d=>d.id===payload.peerId&&!d.revoked);if(!peer)throw Error('Device revoked');const c=payload.command;if(c.type.startsWith('provider.')||['connector.save','connector.remove'].includes(c.type))return{id:c.id,ok:false,error:{code:'DESKTOP_ONLY',message:'Configure provider and connector credentials on the desktop'}};return command(c.type,c.payload,c.id);}throw Error('Unknown remote operation');});
 win.on('hide',()=>{cancelSpeech();if(!win.isDestroyed())win.webContents.send('fox:event',{type:'speech.stopped'});});win.webContents.on('render-process-gone',()=>cancelSpeech());
 await background.loadFile(join(__dirname,'renderer/index.html'),{hash:'remote'});await win.loadFile(join(__dirname,'renderer/index.html'));
}).catch(error=>{dialog.showErrorBox('Fox Bot could not start',error.message);quitting=true;app.quit();});
let shutdownStarted=false,shutdownComplete=false;
app.on('before-quit',event=>{quitting=true;if(shutdownComplete)return;event.preventDefault();if(shutdownStarted)return;shutdownStarted=true;cancelSpeech();relay?.stop();const finish=()=>{if(shutdownComplete)return;shutdownComplete=true;native?.close();app.quit();};if(!worker){finish();return;}const timeout=setTimeout(()=>{worker.kill();finish();},10000);worker.once('exit',()=>{clearTimeout(timeout);finish();});worker.postMessage({type:'shutdown'});});
app.on('window-all-closed',()=>{if(quitting)app.quit();});
