import {app,BrowserWindow,ipcMain,utilityProcess,shell,dialog,nativeImage,Tray,Menu,session,desktopCapturer,screen} from 'electron';
import {randomUUID} from 'node:crypto';
import {mkdirSync,readFileSync,writeFileSync,existsSync} from 'node:fs';
import {join,resolve,basename} from 'node:path';
import QRCode from 'qrcode';
import {Vault} from './vault';
import {chatgptSignIn,openrouterConnect} from './auth';
import {NativeHelper} from './native';
import {HostRelay} from './relay';
import type {CommandResult} from '@foxbot/protocol';
let win:BrowserWindow,background:BrowserWindow,tray:Tray,worker:ReturnType<typeof utilityProcess.fork>,vault:Vault,native:NativeHelper,relay:HostRelay|undefined;let quitting=false;
const waiting=new Map<string,{resolve:(r:CommandResult)=>void,reject:(e:Error)=>void}>();let ready:Promise<void>;let readyResolve:()=>void;
const dir=()=>app.getPath('userData');
function broadcast(event:any){if(win&&!win.isDestroyed())win.webContents.send('fox:event',event);if(background&&!background.isDestroyed())background.webContents.send('fox:event',event);}
async function command(type:string,payload:any,commandId=randomUUID()):Promise<CommandResult>{await ready;const requestId=randomUUID();return new Promise((resolve,reject)=>{waiting.set(requestId,{resolve,reject});worker.postMessage({type:'command',requestId,command:{version:1,id:commandId,type,payload}});});}
function trust(event:Electron.IpcMainInvokeEvent,remote=false){if(event.sender!==win.webContents && !(remote&&event.sender===background.webContents))throw Error('Untrusted IPC sender');if(!event.senderFrame?.url.startsWith('file:'))throw Error('Untrusted frame');}
function getRelay(){if(!relay)relay=new HostRelay(dir(),vault,m=>win.webContents.send('fox:remote',m),m=>background.webContents.send('fox:remote',m));return relay;}
function protect(w:BrowserWindow){w.webContents.setWindowOpenHandler(({url})=>{if(/^https?:/.test(url))void shell.openExternal(url);return{action:'deny'};});w.webContents.on('will-navigate',(e,url)=>{if(!url.startsWith('file:'))e.preventDefault();});}
async function nativeRequest(method:string,args:any){if(method==='input'){const display=screen.getPrimaryDisplay();if(args.kind==='click'){const dip={x:Math.round(display.bounds.x+args.x*display.bounds.width),y:Math.round(display.bounds.y+args.y*display.bounds.height)};const point=process.platform==='win32'?screen.dipToScreenPoint(dip):dip;return native.call('click',point);}if(args.kind==='text')return native.call('type',{text:args.text});if(args.kind==='key')return native.call('key',{key:args.key});if(args.kind==='scroll')return native.call('scroll',{amount:args.amount});throw Error('Invalid input');}return native.call(method,args);}
app.whenReady().then(async()=>{
 mkdirSync(dir(),{recursive:true});vault=new Vault(dir());native=new NativeHelper(app.isPackaged?join(process.resourcesPath,'native'):resolve(__dirname,'../../../native/target/release'));
 ready=new Promise(r=>readyResolve=r);worker=utilityProcess.fork(join(__dirname,'worker.cjs'),[dir()],{serviceName:'Fox Bot runtime'});
 worker.on('message',async(m:any)=>{if(m.type==='ready'){readyResolve();return;}if(m.type==='result'){waiting.get(m.requestId)?.resolve(m.result);waiting.delete(m.requestId);}if(m.type==='event')broadcast(m.event);if(m.type==='credential'||m.type==='native'){try{const data=m.type==='credential'?vault.get('provider:'+m.data.id):await nativeRequest(m.data.method,m.data.args);worker.postMessage({type:'host.result',id:m.id,data});}catch(e:any){worker.postMessage({type:'host.result',id:m.id,error:e.message});}}});
 worker.on('exit',()=>{for(const p of waiting.values())p.reject(Error('Fox Bot runtime stopped'));waiting.clear();broadcast({type:'runtime.stopped'});});
 win=new BrowserWindow({width:1250,height:860,minWidth:800,minHeight:600,title:'Fox Bot',backgroundColor:'#080808',autoHideMenuBar:true,webPreferences:{preload:join(__dirname,'preload.cjs'),nodeIntegration:false,contextIsolation:true,sandbox:true}});protect(win);
 background=new BrowserWindow({show:false,width:1,height:1,webPreferences:{preload:join(__dirname,'preload.cjs'),nodeIntegration:false,contextIsolation:true,sandbox:true,backgroundThrottling:false}});protect(background);
 session.defaultSession.setPermissionRequestHandler((contents,permission,callback)=>callback(contents===background.webContents&&permission==='media'));
 session.defaultSession.setDisplayMediaRequestHandler(async(request,callback)=>{if(request.frame!==background.webContents.mainFrame){callback({});return;}const sources=await desktopCapturer.getSources({types:['screen']});const primary=String(screen.getPrimaryDisplay().id);callback({video:sources.find(s=>s.display_id===primary)??sources[0]});});
 const icon=nativeImage.createFromDataURL('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+j1ioAAAAASUVORK5CYII=').resize({width:16,height:16});tray=new Tray(icon);tray.setToolTip('Fox Bot — local runtime');tray.setContextMenu(Menu.buildFromTemplate([{label:'Open Fox Bot',click:()=>win.show()},{label:'Emergency stop',click:()=>void command('emergency.stop',{})},{label:'Quit Fox Bot',click:()=>{quitting=true;app.quit();}}]));tray.on('click',()=>win.show());win.on('close',e=>{if(!quitting){e.preventDefault();win.hide();}});
 ipcMain.handle('fox:command',(event,{type,payload})=>{trust(event);return command(type,payload);});
 ipcMain.handle('fox:desktop',async(event,{type,payload})=>{trust(event);try{
  if(type==='status'){const identityFile=join(dir(),'identity.json');return{ok:true,data:{secureStorage:vault.available(),identity:existsSync(identityFile)?JSON.parse(readFileSync(identityFile,'utf8')):null,chatgptAvailable:!!(process.env.FOX_CHATGPT_CLIENT_ID&&process.env.FOX_CHATGPT_ISSUER),version:app.getVersion(),workspace:join(dir(),'workspace'),remote:relay?.status()??null}};}
  if(type==='auth.chatgpt'){if(!process.env.FOX_CHATGPT_CLIENT_ID||!process.env.FOX_CHATGPT_ISSUER)throw Error('Official ChatGPT client registration is required. Configure FOX_CHATGPT_CLIENT_ID and FOX_CHATGPT_ISSUER.');const identity=await chatgptSignIn({clientId:process.env.FOX_CHATGPT_CLIENT_ID,issuer:process.env.FOX_CHATGPT_ISSUER,redirectUri:process.env.FOX_CHATGPT_REDIRECT_URI??'http://127.0.0.1:42173/callback'},url=>shell.openExternal(url));writeFileSync(join(dir(),'identity.json'),JSON.stringify(identity),{mode:0o600});return{ok:true,data:identity};}
  if(type==='provider.save'){const id=payload.id??randomUUID();if(payload.key)vault.set('provider:'+id,payload.key);const {key,...profile}=payload;return await command('provider.save',{...profile,id,hasCredential:!!vault.get('provider:'+id)});}
  if(type==='provider.openrouter'){const key=await openrouterConnect(url=>shell.openExternal(url));const id=randomUUID();vault.set('provider:'+id,key);return await command('provider.save',{id,kind:'openrouter',name:'OpenRouter',hasCredential:true});}
  if(type==='attachment.pick'){const selection=await dialog.showOpenDialog(win,{properties:['openFile','multiSelections']});if(selection.canceled)return{ok:true,data:[]};const attachments=[];for(const path of selection.filePaths.slice(0,6)){const bytes=readFileSync(path);if(bytes.length>25*1024*1024)throw Error('Attachment exceeds 25 MB');const extension=path.split('.').at(-1)?.toLowerCase();const mime=({png:'image/png',jpg:'image/jpeg',jpeg:'image/jpeg',pdf:'application/pdf',txt:'text/plain',md:'text/markdown',csv:'text/csv'} as any)[extension??'']??'application/octet-stream';const result=await command('attachment.upload',{name:basename(path),mime,base64:bytes.toString('base64')});if(!result.ok)throw Error(result.error?.message);attachments.push(result.data);}return{ok:true,data:attachments};}
  if(type==='workspace.open'){await shell.openPath(join(dir(),'workspace'));return{ok:true};}
  if(type==='template.export'){const s:any=(await command('snapshot',{})).data;const b=s.bots.find((b:any)=>b.id===payload.id);if(!b)throw Error('Bot not found');const selection=await dialog.showSaveDialog(win,{defaultPath:b.name+'.foxbot.json'});if(selection.filePath){const {id,providerId,revision,createdAt,...publicBot}=b;writeFileSync(selection.filePath,JSON.stringify({version:1,bot:publicBot},null,2));}return{ok:true};}
  if(type==='template.import'){const selection=await dialog.showOpenDialog(win,{properties:['openFile'],filters:[{name:'Fox Bot template',extensions:['json']}]});if(selection.canceled)return{ok:true};const template=JSON.parse(readFileSync(selection.filePaths[0],'utf8'));if(template.version!==1)throw Error('Unsupported template');return command('bot.create',{...template.bot,providerId:''});}
  if(type==='artifact.open'){const result=await command('artifact.read',{id:payload.id});if(!result.ok)return result;const a:any=result.data;const selected=await dialog.showSaveDialog(win,{defaultPath:basename(a.name)});if(selected.filePath){writeFileSync(selected.filePath,Buffer.from(a.base64,'base64'));await shell.openPath(selected.filePath);}return{ok:true};}
  if(type==='remote.configure'){const r=getRelay();r.configure(payload.endpoint,payload.token);r.start();return{ok:true,data:r.status()};}
  if(type==='remote.status')return{ok:true,data:getRelay().status()};
  if(type==='remote.pairing'){const offer=getRelay().pairing();return{ok:true,data:{offer,qr:await QRCode.toDataURL(JSON.stringify(offer))}};}
  if(type==='remote.approve'){getRelay().approve(payload.peerId,payload.approved);return{ok:true};}
  if(type==='remote.revoke'){getRelay().revoke(payload.id);return{ok:true};}
  throw Error('Unknown desktop operation');
 }catch(e:any){return{ok:false,error:{message:e.message}};}});
 ipcMain.handle('fox:remote',async(event,{type,payload})=>{trust(event,true);if(event.sender!==background.webContents)throw Error('Remote bridge restricted to background');if(type==='signal'){getRelay().signal(payload);return;}if(type==='command'){const peer=getRelay().devices.find(d=>d.id===payload.peerId&&!d.revoked);if(!peer)throw Error('Device revoked');const c=payload.command;if(c.type.startsWith('provider.'))return{id:c.id,ok:false,error:{code:'DESKTOP_ONLY',message:'Configure providers on the desktop'}};return command(c.type,c.payload,c.id);}throw Error('Unknown remote operation');});
 await background.loadFile(join(__dirname,'renderer/index.html'),{hash:'remote'});await win.loadFile(join(__dirname,'renderer/index.html'));
}).catch(error=>{dialog.showErrorBox('Fox Bot could not start',error.message);quitting=true;app.quit();});
app.on('before-quit',()=>{quitting=true;relay?.stop();native?.close();worker?.postMessage({type:'shutdown'});});
app.on('window-all-closed',()=>{if(quitting)app.quit();});
