import WebSocket from 'ws';
import {generateKeyPairSync,randomUUID,randomBytes,createHash,sign,verify,createPublicKey} from 'node:crypto';
import {readFileSync,writeFileSync,existsSync} from 'node:fs';
import {join} from 'node:path';
import type {Vault} from './vault';
interface Trust {id:string;name:string;publicKey:string;createdAt:string;revoked:boolean;}
export class HostRelay {
 socket?:WebSocket;hostId:string;publicKey:string;privateKey:string;endpoint='';devices:Trust[]=[];pending=new Map<string,any>();private configFile:string;private seen=new Map<string,number>();private sessions=new Map<string,string>();private retired:string[]=[];private retry?:ReturnType<typeof setTimeout>;private enabled=false;private offer?:any;
 constructor(dir:string,readonly vault:Vault,readonly notify:(m:any)=>void,readonly background:(m:any)=>void){this.configFile=join(dir,'remote.json');const config=existsSync(this.configFile)?JSON.parse(readFileSync(this.configFile,'utf8')):{};this.hostId=config.hostId??randomUUID();this.endpoint=config.endpoint??'';this.devices=config.devices??[];this.retired=config.retired??[];let key=this.vault.get('remote.identity');if(!key){const pair=generateKeyPairSync('ec',{namedCurve:'prime256v1'});key=JSON.stringify({publicKey:pair.publicKey.export({type:'spki',format:'der'}).toString('base64'),privateKey:pair.privateKey.export({type:'pkcs8',format:'pem'}).toString()});this.vault.set('remote.identity',key);}const identity=JSON.parse(key);this.publicKey=identity.publicKey;this.privateKey=identity.privateKey;this.save();}
 save(){writeFileSync(this.configFile,JSON.stringify({hostId:this.hostId,endpoint:this.endpoint,devices:this.devices,retired:this.retired}),{mode:0o600});}
 status(){return{hostId:this.hostId,endpoint:this.endpoint,connected:this.socket?.readyState===WebSocket.OPEN,devices:this.devices,pending:[...this.pending.values()]};}
 configure(endpoint:string,token:string){const url=new URL(endpoint);if(url.protocol!=='wss:' && !(url.protocol==='ws:'&&['127.0.0.1','localhost'].includes(url.hostname)))throw Error('Use wss:// or a loopback development server');if(url.pathname!=='/ws'||url.search||url.username||url.password)throw Error('Relay URL must end in /ws and contain no credentials');this.endpoint=endpoint;if(token)this.vault.set('remote.token',token);this.save();}
 signature(value:unknown){return sign('sha256',Buffer.from(JSON.stringify(value)),this.privateKey).toString('base64');}
 send(m:any){if(this.socket?.readyState!==WebSocket.OPEN)throw Error('Relay disconnected');this.socket.send(JSON.stringify(m));}
 start(){if(!this.endpoint)throw Error('Configure a self-hosted relay first');this.stop();this.enabled=true;this.connect();}
 private connect(){this.socket=new WebSocket(this.endpoint,{maxPayload:128*1024});this.socket.on('message',raw=>{try{const m=JSON.parse(raw.toString());this.receive(m);}catch{this.notify({type:'error',message:'Invalid relay message'});}});this.socket.on('error',()=>this.notify({type:'error',message:'Relay connection failed'}));this.socket.on('close',()=>{for(const s of this.sessions.values())this.retired.push(s);this.sessions.clear();this.seen.clear();this.retired=this.retired.slice(-1000);this.save();this.background({type:'disconnect'});this.notify({type:'status',...this.status()});if(this.enabled)this.retry=setTimeout(()=>this.connect(),5000);});}
 private receive(m:any){
  if(m.type==='challenge'){const nonce=String(m.nonce);this.send({type:'register',id:this.hostId,publicKey:this.publicKey,nonce,signature:this.signature([1,'register',this.hostId,this.hostId,nonce]),token:this.vault.get('remote.token')});return;}
  if(m.type==='registered'){this.notify({type:'status',...this.status()});this.send({type:'turn'});if(this.offer&&this.offer.expiresAt>Date.now())this.send({type:'offer',secret:this.offer.secret,expiresAt:this.offer.expiresAt});return;}
  if(m.type==='turn'){this.background({type:'turn',iceServers:m.iceServers});return;}
  if(m.type==='pair_request'){if(!this.offer || this.offer.expiresAt<Date.now())return;if(typeof m.peerId!=='string'||typeof m.publicKey!=='string')return;const code=createHash('sha256').update(JSON.stringify([1,'pair-code',this.hostId,this.publicKey,m.peerId,m.publicKey])).digest('hex').slice(0,8);this.pending.set(m.peerId,{...m,code});this.notify({type:'pair_request',...m,code});return;}
  if(m.type==='pair_approved'){const p=this.pending.get(m.peerId);if(!p || p.publicKey!==m.publicKey)return;this.devices.push({id:p.peerId,name:p.name,publicKey:p.publicKey,revoked:false,createdAt:new Date().toISOString()});this.pending.delete(p.peerId);this.offer=undefined;this.save();this.notify({type:'status',...this.status()});return;}
  if(m.type==='signal'){const peer=this.devices.find(d=>d.id===m.from&&!d.revoked);if(!peer||m.to!==this.hostId||!['offer','answer','ice'].includes(m.kind)||typeof m.payload!=='string'||!Number.isInteger(m.seq))return;const input=[1,'signal',m.from,m.to,m.sessionId,m.seq,m.kind,m.payload];if(!verify('sha256',Buffer.from(JSON.stringify(input)),createPublicKey({key:Buffer.from(peer.publicKey,'base64'),type:'spki',format:'der'}),Buffer.from(m.signature,'base64')))return;
   const key=m.from+':'+m.sessionId;if(m.seq<=(this.seen.get(key)??0))return;if(m.kind==='offer'){if(this.retired.includes(m.sessionId))return;const old=this.sessions.get(m.from);if(old && old!==m.sessionId){this.retired.push(old);this.save();}this.sessions.set(m.from,m.sessionId);}else if(this.sessions.get(m.from)!==m.sessionId)return;this.seen.set(key,m.seq);this.background(m);return;}
  if(m.type==='error')this.notify({type:'error',message:'Relay: '+m.code});
 }
 pairing(){const expiresAt=Date.now()+300000;this.offer={version:1,hostId:this.hostId,endpoint:this.endpoint,secret:randomBytes(32).toString('base64url'),expiresAt,publicKey:this.publicKey};this.send({type:'offer',secret:this.offer.secret,expiresAt});return this.offer;}
 approve(peerId:string,approved:boolean){if(!this.pending.has(peerId))throw Error('Pairing request missing');this.send({type:'approve',peerId,approved});if(!approved)this.pending.delete(peerId);}
 signal(m:any){if(!this.devices.some(d=>d.id===m.to&&!d.revoked) || this.sessions.get(m.to)!==m.sessionId)throw Error('Untrusted device/session');const signed={type:'signal',...m,signature:this.signature([1,'signal',this.hostId,m.to,m.sessionId,m.seq,m.kind,m.payload])};this.send(signed);}
 revoke(id:string){const d=this.devices.find(d=>d.id===id);if(!d)throw Error('Unknown device');d.revoked=true;this.save();this.background({type:'revoke',id});if(this.socket?.readyState===WebSocket.OPEN)this.send({type:'revoke',peerId:id});}
 stop(){this.enabled=false;clearTimeout(this.retry);this.socket?.removeAllListeners();this.socket?.close();this.socket=undefined;this.background({type:'disconnect'});}
}
