import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync,mkdirSync,writeFileSync,symlinkSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {randomUUID} from 'node:crypto';
import {createServer} from 'node:http';
import {Engine,type EngineDeps} from '../apps/desktop/runtime/engine';
const secret='synthetic-connector-key-never-real';
const delay=(ms:number)=>new Promise(r=>setTimeout(r,ms));
async function until(fn:()=>boolean){for(let i=0;i<200;i++){if(fn())return;await delay(10);}throw Error('Timed out waiting for connector engine state');}
function setup(fetcher:typeof fetch=async()=>Response.json({ok:true})){const dir=mkdtempSync(join(tmpdir(),'fox-connector-engine-'));const events:any[]=[];const deps:EngineDeps={credential:async()=>'',connectorCredential:async()=>secret,publish:e=>events.push(e),connectorFetch:fetcher};const e=new Engine(dir,deps);const cmd=(type:string,payload:any={})=>e.command({version:1,id:randomUUID(),type,payload});return{dir,e,cmd,deps,events,close:async()=>{await e.close();rmSync(dir,{recursive:true,force:true});}};}
const manifest={id:'custom',name:'Custom API',kind:'http',baseUrl:'https://example.com',enabled:true,grantedScopes:[],tools:[{name:'write',description:'Create a record',method:'POST',path:'/records',parameters:{type:'object',properties:{text:{type:'string'}},required:['text'],additionalProperties:false},scopes:[],approval:false}]} as const;
async function provider(s:ReturnType<typeof setup>,toolName='connector_custom__write',args={text:'Hello'}){let submitted:any;const server=createServer((req,res)=>{let raw='';req.on('data',b=>raw+=b);req.on('end',()=>{const body=JSON.parse(raw);submitted=body;const delta=body.messages.some((m:any)=>m.role==='tool')?{content:'Complete'}:{tool_calls:[{index:0,id:'connector-call',function:{name:toolName,arguments:JSON.stringify(args)}}]};res.end(`data: ${JSON.stringify({choices:[{delta}]})}\n\ndata: [DONE]\n\n`);});});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const profile:any=(await s.cmd('provider.save',{kind:'compatible',name:'Local fixture',baseUrl:`http://127.0.0.1:${(server.address() as any).port}`})).data;const b=s.e.snapshot().bots[0];await s.cmd('bot.update',{id:b.id,revision:b.revision,providerId:profile.id,model:'fixture'});return{last:()=>submitted,close:async()=>{server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));}};}

test('connector manifests persist separately, startup registers them and runtime rejects embedded keys',async()=>{const s=setup();try{assert.equal((await s.cmd('connector.save',{...manifest,key:secret})).ok,false);assert.equal((await s.cmd('connector.save',manifest)).ok,true);assert.equal('connectors' in s.e.snapshot(),false);assert.equal(JSON.stringify((await s.cmd('connector.list')).data).includes(secret),false);await s.e.close();const reopened=new Engine(s.dir,s.deps);try{assert.equal(reopened.connectors.connections.size,1);const result=await reopened.command({version:1,id:randomUUID(),type:'connector.tools',payload:{}});assert.ok((result.data as any[]).some(t=>t.function.name==='connector_custom__write'));}finally{await reopened.close();}}finally{await s.close();}});

test('connector save retries deduplicate and invalid replacement preserves old configuration',async()=>{const s=setup();try{const command={version:1,id:randomUUID(),type:'connector.save',payload:manifest};const first=await s.e.command(command);assert.deepEqual(await s.e.command({...command,payload:{...manifest,name:'Changed'}}),first);assert.equal((await s.cmd('connector.save',{...manifest,baseUrl:'http://external.example'})).ok,false);assert.equal(s.e.connectors.connections.get('custom')?.name,manifest.name);assert.equal((await s.cmd('connector.remove',{id:'custom'})).ok,true);assert.deepEqual((await s.cmd('connector.list')).data,[]);assert.deepEqual((await s.cmd('connector.tools')).data,[]);}finally{await s.close();}});

test('agent discovers connector tools, owner approval gates external POST and credentials never enter model history',async()=>{const requests:any[]=[];const s=setup(async(url,init)=>{requests.push({url,init});return Response.json({ok:true,echo:secret});});const p=await provider(s);try{await s.cmd('connector.save',manifest);await s.cmd('message.send',{conversationId:s.e.snapshot().conversations[0].id,content:'Create a record'});await until(()=>s.e.snapshot().approvals.length===1);assert.equal(requests.length,0);assert.equal(s.e.snapshot().runs[0].status,'awaiting_approval');assert.match(s.e.snapshot().approvals[0].summary,/custom: write/);await s.cmd('approval.resolve',{id:s.e.snapshot().approvals[0].id,approved:true});await until(()=>s.e.active.size===0);assert.equal(requests.length,1);assert.equal(requests[0].init.method,'POST');assert.equal(requests[0].init.headers.Authorization,`Bearer ${secret}`);assert.ok(p.last().tools.some((t:any)=>t.function.name==='connector_custom__write'));assert.equal(JSON.stringify(p.last()).includes(secret),false);assert.match(s.e.snapshot().tools[0].output??'',/redacted/);}finally{await p.close();await s.close();}});

test('connector rejection and disconnect during approval cause no external action',async()=>{for(const action of ['reject','remove'] as const){let requests=0;const s=setup(async()=>{requests++;return Response.json({ok:true});}),p=await provider(s);try{await s.cmd('connector.save',manifest);await s.cmd('message.send',{conversationId:s.e.snapshot().conversations[0].id,content:'Create'});await until(()=>s.e.snapshot().approvals.length===1);if(action==='remove')await s.cmd('connector.remove',{id:'custom'});await s.cmd('approval.resolve',{id:s.e.snapshot().approvals[0].id,approved:action==='remove'});await until(()=>s.e.active.size===0);assert.equal(requests,0);assert.equal(s.e.snapshot().tools[0].status,'failed');assert.match(s.e.snapshot().tools[0].output??'',action==='reject'?/owner rejected/:/not connected/);}finally{await p.close();await s.close();}}});

test('engine routes read-only connector calls without approval and enforces declared scope',async()=>{let requests=0;const s=setup(async()=>{requests++;return Response.json({records:['a']});});const p=await provider(s,'connector_custom__read',{} as any);try{await s.cmd('connector.save',{...manifest,grantedScopes:['read'],tools:[{name:'read',description:'Read',method:'GET',path:'/records',parameters:{type:'object',properties:{},additionalProperties:false},scopes:['read']}]});await s.cmd('message.send',{conversationId:s.e.snapshot().conversations[0].id,content:'Read'});await until(()=>s.e.active.size===0);assert.equal(requests,1);assert.equal(s.e.snapshot().approvals.length,0);assert.equal(s.e.snapshot().tools[0].status,'completed');}finally{await p.close();await s.close();}});

test('event routines seed cursors without history and atomically deduplicate replayed events',async()=>{let historyId='10';const s=setup(async(url)=>{const value=String(url);if(value.endsWith('/profile'))return Response.json({historyId});assert.ok(value.includes('/history?'));return Response.json({historyId:'11',history:[{id:'11',messagesAdded:[{message:{id:'message-1',threadId:'thread-1'}}]},{id:'11',messagesAdded:[{message:{id:'message-1',threadId:'thread-1'}}]}]});});try{await s.cmd('connector.save',{id:'mail',name:'Gmail',kind:'gmail',grantedScopes:['https://www.googleapis.com/auth/gmail.readonly']});const b=s.e.snapshot().bots[0];const routine:any=(await s.cmd('connector.routine.save',{botId:b.id,connectionId:'mail',name:'New mail',prompt:'Summarize this new message.',eventTypes:['gmail.message_added'],enabled:true})).data;assert.equal((await s.cmd('connector.poll',{id:'mail'})).ok,true);assert.equal(s.e.snapshot().runs.length,0);assert.equal(s.e.store.get('connector_cursors','connector:mail').value,'10');await s.cmd('connector.poll',{id:'mail'});await until(()=>s.e.active.size===0);assert.equal(s.e.snapshot().runs.length,1);assert.equal(s.e.store.get('connector_cursors','connector:mail').value,'11');assert.equal(s.e.store.list('connector_events').length,1);assert.ok(s.e.snapshot().messages.some(m=>m.content.includes('untrusted data')));s.e.store.put('connector_cursors',{id:'connector:mail',value:'10'});await s.cmd('connector.poll',{id:'mail'});assert.equal(s.e.snapshot().runs.length,1);assert.equal((await s.cmd('connector.routine.list')).ok,true);await s.cmd('connector.routine.remove',{id:routine.id});assert.deepEqual((await s.cmd('connector.routine.list')).data,[]);}finally{await s.close();}});

test('event polling aborts on emergency stop and cannot enqueue while stopped',async()=>{const s=setup(async(_url,init)=>new Promise<Response>((_resolve,reject)=>{const abort=()=>reject(new DOMException('aborted','AbortError'));if(init?.signal?.aborted)abort();else init?.signal?.addEventListener('abort',abort,{once:true});}));try{await s.cmd('connector.save',{id:'mail',name:'Gmail',kind:'gmail',grantedScopes:['https://www.googleapis.com/auth/gmail.readonly']});const poll=s.cmd('connector.poll',{id:'mail'});await until(()=>s.e.polls.size===1);await s.cmd('emergency.stop');assert.equal((await poll).ok,false);assert.equal(s.e.snapshot().runs.length,0);assert.equal((await s.cmd('connector.poll',{id:'mail'})).ok,false);await s.cmd('emergency.resume');assert.equal(s.e.pollController.signal.aborted,false);}finally{await s.close();}});

test('workspace tools reject explicit browser profiles and symlink aliases into them',async()=>{const s=setup();try{const profile=join(s.dir,'workspace','.browser','bot');mkdirSync(profile,{recursive:true});writeFileSync(join(profile,'Cookies'),'private-cookie');await assert.rejects(s.e.tools.safePath('.browser/bot/Cookies'),/Browser profiles are private/);await assert.rejects(s.e.tools.safePath('.browser/new/file',true),/Browser profiles are private/);symlinkSync(profile,join(s.dir,'workspace','alias'),process.platform==='win32'?'junction':'dir');await assert.rejects(s.e.tools.safePath('alias/Cookies'),/Browser profiles are private/);await assert.rejects(s.e.tools.safePath('alias/new-file',true),/Browser profiles are private/);}finally{await s.close();}});
