import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync,symlinkSync,mkdirSync,readFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {randomUUID} from 'node:crypto';
import http from 'node:http';
import {Engine} from '../apps/desktop/runtime/engine';
const delay=(ms:number)=>new Promise(r=>setTimeout(r,ms));
function setup(){const dir=mkdtempSync(join(tmpdir(),'foxbot-test-'));const events:any[]=[];const e=new Engine(dir,{credential:async()=>'',publish:event=>events.push(event)});const cmd=(type:string,payload:any={},id=randomUUID())=>e.command({version:1,id,type,payload});return{dir,e,cmd,events,close:async()=>{await e.close();rmSync(dir,{recursive:true,force:true});}};}
test('bot mutations persist, revision conflicts refuse overwrite, retries deduplicate',async()=>{const s=setup();try{const id=randomUUID();const a=await s.cmd('bot.create',{name:'Research'},id);assert.equal(a.ok,true);assert.deepEqual(await s.cmd('bot.create',{name:'Different'},id),a);const b:any=a.data;const update=await s.cmd('bot.update',{id:b.id,revision:1,name:'Evidence'});assert.equal(update.ok,true);const conflict=await s.cmd('bot.update',{id:b.id,revision:1,name:'Stale'});assert.equal(conflict.error?.code,'REVISION_CONFLICT');assert.equal(s.e.snapshot().bots.find(x=>x.id===b.id)?.name,'Evidence');assert.equal(s.e.snapshot().bots.length,2);}finally{await s.close();}});
test('bad command fields, unknown references and provider kinds are rejected',async()=>{const s=setup();try{assert.equal((await s.cmd('bot.create',{name:''})).ok,false);assert.equal((await s.cmd('message.send',{conversationId:randomUUID(),content:'hello'})).ok,false);assert.equal((await s.cmd('provider.save',{name:'Unknown',kind:'bad'})).ok,false);}finally{await s.close();}});
test('search finds persisted messages and drafts do not create runs',async()=>{const s=setup();try{const c=s.e.snapshot().conversations[0];await s.cmd('draft.save',{conversationId:c.id,text:'Draft only'});assert.equal(s.e.snapshot().conversations[0].draft,'Draft only');assert.equal(s.e.snapshot().runs.length,0);const r=await s.cmd('message.send',{conversationId:c.id,content:'Quartz research'});assert.equal(r.ok,true);await delay(30);assert.equal((await s.cmd('search',{text:'Quartz'})).ok,true);assert.equal(s.e.snapshot().runs[0].status,'failed');assert.match(s.e.snapshot().runs[0].error??'',/Connect an AI provider/);}finally{await s.close();}});
test('deletion removes bot conversations, memory and routines while preserving shared files',async()=>{const s=setup();try{const b=s.e.snapshot().bots[0];await s.cmd('memory.save',{botId:b.id,text:'Preference',enabled:true});await s.cmd('routine.save',{botId:b.id,name:'Daily',prompt:'Research',cron:'0 8 * * *',timezone:'Europe/Athens',enabled:true});const path=await s.e.tools.safePath('keep.txt',true);await import('node:fs/promises').then(fs=>fs.writeFile(path,'keep'));const r=await s.cmd('bot.delete',{id:b.id});assert.equal(r.ok,true);assert.equal(s.e.snapshot().bots.length,0);assert.equal(s.e.snapshot().conversations.length,0);assert.equal(s.e.snapshot().memories.length,0);assert.equal(s.e.snapshot().routines.length,0);assert.equal(readFileSync(path,'utf8'),'keep');}finally{await s.close();}});
test('workspace rejects traversal and escaping symlinks',async()=>{const s=setup();try{await assert.rejects(s.e.tools.safePath('../secret.txt',true),/leaves/);const outside=join(s.dir,'outside');mkdirSync(outside);const inside=join(s.dir,'workspace','escape');symlinkSync(outside,inside,process.platform==='win32'?'junction':'dir');await assert.rejects(s.e.tools.safePath('escape/file',true),/Symlink/);}finally{await s.close();}});
test('routine downtime skips missed work and advances schedule',async()=>{const s=setup();try{const b=s.e.snapshot().bots[0];const r:any=(await s.cmd('routine.save',{botId:b.id,name:'Daily',prompt:'Task',cron:'0 8 * * *',timezone:'Europe/Athens',enabled:true})).data;s.e.store.put('routines',{...r,nextRun:new Date(Date.now()-120000).toISOString()});s.e.tick();assert.equal(s.e.snapshot().runs.length,0);assert.ok(s.events.some(e=>e.type==='routine.missed'));assert.ok(Date.parse(s.e.snapshot().routines[0].nextRun)>Date.now());assert.equal((await s.cmd('routine.save',{botId:b.id,name:'Bad',prompt:'Task',cron:'bad',timezone:'invalid',enabled:true})).ok,false);}finally{await s.close();}});
test('streamed tool execution waits for approval, rejection performs no write',async()=>{const s=setup();let requests=0;const server=http.createServer((req,res)=>{let raw='';req.on('data',b=>raw+=b);req.on('end',()=>{const body=JSON.parse(raw);requests++;res.setHeader('Content-Type','text/event-stream');if(body.messages.some((m:any)=>m.role==='tool'))res.end('data: '+JSON.stringify({choices:[{delta:{content:'Action reviewed.'}}]})+'\n\ndata: [DONE]\n\n');else res.end('data: '+JSON.stringify({choices:[{delta:{tool_calls:[{index:0,id:'tool-1',function:{name:'workspace_write',arguments:JSON.stringify({path:'blocked.txt',content:'must not be written'})}}]}}]})+'\n\ndata: [DONE]\n\n');});});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));try{const port=(server.address() as any).port;const p:any=(await s.cmd('provider.save',{kind:'compatible',name:'Fixture',baseUrl:`http://127.0.0.1:${port}`})).data;const b=s.e.snapshot().bots[0];await s.cmd('bot.update',{id:b.id,revision:1,providerId:p.id,model:'fixture'});await s.cmd('message.send',{conversationId:s.e.snapshot().conversations[0].id,content:'Write a file'});for(let i=0;i<100&&!s.e.snapshot().approvals.length;i++)await delay(10);assert.equal(s.e.snapshot().runs[0].status,'awaiting_approval');const a=s.e.snapshot().approvals[0];assert.ok(a);assert.equal((await s.cmd('approval.resolve',{id:a.id,approved:false})).ok,true);for(let i=0;i<100&&s.e.snapshot().runs[0].status!=='completed';i++)await delay(10);assert.equal(s.e.snapshot().runs[0].status,'completed');assert.equal(requests,2);await assert.rejects(s.e.tools.safePath('blocked.txt'),/ENOENT/);}finally{await new Promise<void>(r=>server.close(()=>r()));await s.close();}});
test('attachment metadata is persisted without exposing disk paths in snapshot',async()=>{const s=setup();try{const a=await s.cmd('attachment.upload',{name:'context.txt',mime:'text/plain',base64:Buffer.from('hello').toString('base64')});assert.equal(a.ok,true);assert.equal((a.data as any).size,5);assert.equal('path' in (a.data as any),false);const r=await s.cmd('message.send',{conversationId:s.e.snapshot().conversations[0].id,content:'Read it',attachments:[a.data]});assert.equal(r.ok,true);await delay(20);}finally{await s.close();}});
