import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync,writeFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {randomUUID} from 'node:crypto';
import {createServer} from 'node:http';
import {Engine} from '../apps/desktop/runtime/engine';
import {Tools,definitions,approvalTools} from '../apps/desktop/runtime/tools';
const delay=(ms:number)=>new Promise(r=>setTimeout(r,ms));
async function until(fn:()=>boolean){for(let i=0;i<200;i++){if(fn())return;await delay(10);}throw Error('Timed out waiting for fixture state');}
function setup(){const dir=mkdtempSync(join(tmpdir(),'fox-native-agent-')),calls:{method:string,args:any}[]=[];const e=new Engine(dir,{credential:async()=>'',publish:()=>{},native:async(method,args)=>{calls.push({method,args});if(method==='capabilities')return{inspect:true,screenshot:true,click:true,type:true,key:true,scroll:true};if(method==='screenshot'){writeFileSync(args.path,Buffer.from('fixture screenshot'));return{path:args.path,mime:'image/bmp',x:-1920,y:0,width:3840,height:1080};}return{sent:true};}});const cmd=(type:string,payload:any={})=>e.command({version:1,id:randomUUID(),type,payload});return{dir,e,calls,cmd,close:async()=>{for(const a of e.active.values())a.abort();for(const fn of e.waiting.values())fn(false);await until(()=>e.active.size===0);await e.close();rmSync(dir,{recursive:true,force:true});}};}
async function provider(s:ReturnType<typeof setup>,name:string,args:any){const server=createServer((req,res)=>{let raw='';req.on('data',b=>raw+=b);req.on('end',()=>{const body=JSON.parse(raw);const delta=body.messages.some((m:any)=>m.role==='tool')?{content:'Done'}:{tool_calls:[{index:0,id:'native-fixture',function:{name,arguments:JSON.stringify(args)}}]};res.end(`data: ${JSON.stringify({choices:[{delta}]})}\n\ndata: [DONE]\n\n`);});});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const profile:any=(await s.cmd('provider.save',{kind:'compatible',name:'Fixture',baseUrl:`http://127.0.0.1:${(server.address() as any).port}`})).data;const bot=s.e.snapshot().bots[0];await s.cmd('bot.update',{id:bot.id,revision:bot.revision,providerId:profile.id,model:'fixture'});return{botId:bot.id,close:async()=>{server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));}};}

test('native tools are advertised and each native input requires approval at the tool boundary',async()=>{const s=setup();try{assert.ok(definitions.some(d=>d.function.name==='native_inspect'));for(const name of ['native_click','native_type','native_key','native_scroll'])assert.ok(approvalTools.has(name));await assert.rejects(s.e.tools.execute('native_click',{x:50,y:60},'bot',new AbortController().signal,'run',false),/requires owner approval/);assert.equal(s.calls.length,0);s.e.tools.releaseNative('run');}finally{await s.close();}});

test('native schema rejects missing coordinates, fractions, unbounded text, unknown keys and extra fields',async()=>{const s=setup();try{for(const [name,args] of [['native_click',{x:1}],['native_click',{x:1.2,y:3}],['native_type',{text:'x'.repeat(32769)}],['native_key',{key:'ctrl+delete'}],['native_scroll',{amount:101}],['native_screenshot',{path:'outside'}]] as const)assert.throws(()=>s.e.tools.validate(name,args));assert.equal(s.calls.length,0);}finally{await s.close();}});

test('engine executes native input only after owner approval and releases run ownership',async()=>{const s=setup(),p=await provider(s,'native_click',{x:-100,y:80});try{await s.cmd('message.send',{conversationId:s.e.snapshot().conversations[0].id,content:'Click fixture'});await until(()=>s.e.snapshot().approvals.length===1);assert.equal(s.calls.length,0);const run=s.e.snapshot().runs[0];assert.equal(s.e.tools.nativeOwner,run.id);await s.cmd('approval.resolve',{id:s.e.snapshot().approvals[0].id,approved:true});await until(()=>s.e.active.size===0);assert.equal(s.e.snapshot().runs[0].status,'completed');assert.deepEqual(s.calls.find(c=>c.method==='click')?.args,{x:-100,y:80});assert.equal(s.e.tools.nativeOwner,undefined);}finally{await p.close();await s.close();}});

test('parallel native runs cannot acquire computer while another run awaits approval',async()=>{const s=setup(),p=await provider(s,'native_key',{key:'enter'});try{await s.cmd('message.send',{conversationId:s.e.snapshot().conversations[0].id,content:'First'});await until(()=>s.e.snapshot().approvals.length===1);const c:any=(await s.cmd('conversation.create',{title:'Second',botIds:[p.botId]})).data;await s.cmd('message.send',{conversationId:c.id,content:'Second'});await until(()=>s.e.snapshot().runs.some(r=>r.conversationId===c.id&&r.status==='completed'));assert.equal(s.e.snapshot().approvals.length,1);assert.ok(s.e.snapshot().tools.some(t=>t.output?.includes('owned by another run')));assert.equal(s.calls.some(c=>c.method==='key'),false);await s.cmd('approval.resolve',{id:s.e.snapshot().approvals[0].id,approved:false});await until(()=>s.e.active.size===0);assert.equal(s.e.tools.nativeOwner,undefined);}finally{await p.close();await s.close();}});

test('invalid native model arguments fail before approval without issuing native requests',async()=>{const s=setup(),p=await provider(s,'native_click',{x:'wrong',y:8});try{await s.cmd('message.send',{conversationId:s.e.snapshot().conversations[0].id,content:'Bad request'});await until(()=>s.e.active.size===0);assert.equal(s.e.snapshot().approvals.length,0);assert.equal(s.calls.length,0);assert.equal(s.e.snapshot().tools[0].status,'failed');}finally{await p.close();await s.close();}});

test('native screenshots become artifacts attributed to their run and include virtual-desktop origin',async()=>{const s=setup(),p=await provider(s,'native_screenshot',{});try{await s.cmd('message.send',{conversationId:s.e.snapshot().conversations[0].id,content:'Capture fixture'});await until(()=>s.e.active.size===0);const state=s.e.snapshot();assert.equal(state.artifacts.length,1);assert.equal(state.artifacts[0].runId,state.runs[0].id);assert.equal(state.artifacts[0].mime,'image/bmp');assert.match(state.tools[0].output??'',/"x":-1920/);assert.equal('path' in state.artifacts[0],false);}finally{await p.close();await s.close();}});

test('emergency stop cancels pending approval, invokes helper stop and requires explicit resume',async()=>{const s=setup(),p=await provider(s,'native_key',{key:'enter'});try{await s.cmd('message.send',{conversationId:s.e.snapshot().conversations[0].id,content:'Wait for approval'});await until(()=>s.e.snapshot().approvals.length===1);assert.equal((await s.cmd('emergency.stop')).ok,true);await until(()=>s.e.active.size===0);assert.equal(s.e.snapshot().runs[0].status,'cancelled');assert.equal(s.e.stopped,true);assert.equal(s.e.tools.nativeStopped,true);assert.ok(s.calls.some(c=>c.method==='emergency_stop'));assert.equal(s.calls.some(c=>c.method==='key'),false);await assert.rejects(s.e.tools.execute('native_key',{key:'enter'},'bot',new AbortController().signal,'new-run',true),/emergency stop/);assert.equal((await s.cmd('emergency.resume')).ok,true);assert.equal(s.e.stopped,false);assert.equal(s.e.tools.nativeStopped,false);assert.ok(s.calls.some(c=>c.method==='resume'));}finally{await p.close();await s.close();}});

test('takeover blocks agent native calls, validates human input and leaves dedicated browser independent',async()=>{const s=setup();try{assert.equal((await s.cmd('computer.input',{kind:'click',x:.5,y:.5})).ok,false);assert.equal((await s.cmd('computer.takeover',{enabled:true})).ok,true);await assert.rejects(s.e.tools.execute('native_inspect',{},'bot',new AbortController().signal,'run'),/human control/);assert.equal((await s.cmd('computer.input',{kind:'click',x:.5})).ok,false);assert.equal((await s.cmd('computer.input',{kind:'click',x:.5,y:.5})).ok,true);assert.ok(s.calls.some(c=>c.method==='input'));(s.e.tools as any).context=async()=>({pages:()=>[{goto:async()=>{},url:()=> 'https://example.com'}]});assert.equal(await s.e.tools.execute('browser_open',{url:'https://example.com'},'bot',new AbortController().signal,'run'),'https://example.com');await s.cmd('emergency.stop');assert.equal((await s.cmd('computer.input',{kind:'key',key:'enter'})).ok,false);assert.equal((await s.cmd('computer.takeover',{enabled:false})).ok,true);assert.equal(s.e.tools.nativeStopped,true);assert.equal((await s.cmd('emergency.resume')).ok,true);}finally{await s.close();}});

test('unsupported capabilities cannot drive native input even when approved',async()=>{const dir=mkdtempSync(join(tmpdir(),'fox-native-disabled-'));const calls:string[]=[];const tools=new Tools(dir,async()=>'',async method=>{calls.push(method);return{click:false,limitations:['Wayland portal unavailable']};});try{await assert.rejects(tools.execute('native_click',{x:0,y:0},'bot',new AbortController().signal,'run',true),/Wayland portal unavailable/);assert.deepEqual(calls,['capabilities']);}finally{await tools.close();rmSync(dir,{recursive:true,force:true});}});

test('human input command retries return cached result without replaying physical input',async()=>{const s=setup();try{await s.cmd('computer.takeover',{enabled:true});const command={version:1,id:randomUUID(),type:'computer.input',payload:{kind:'key',key:'enter'}};const first=await s.e.command(command);assert.equal(first.ok,true);assert.deepEqual(await s.e.command(command),first);assert.equal(s.calls.filter(c=>c.method==='input').length,1);}finally{await s.close();}});

test('shutdown resolves pending approvals and waits for run cleanup before closing SQLite',async()=>{const s=setup(),p=await provider(s,'native_key',{key:'enter'});try{await s.cmd('message.send',{conversationId:s.e.snapshot().conversations[0].id,content:'Wait'});await until(()=>s.e.snapshot().approvals.length===1);assert.equal(s.e.tasks.size,1);await s.e.close();assert.equal(s.e.tasks.size,0);assert.equal(s.e.active.size,0);assert.equal(s.e.tools.nativeOwner,undefined);assert.equal(s.e.closed,true);assert.equal(s.calls.some(c=>c.method==='key'),false);}finally{await p.close();await s.close();}});
