import type {ProviderProfile,Model,Capabilities} from '@foxbot/protocol';
export const defaults:Record<string,string>={openrouter:'https://openrouter.ai/api/v1',openai:'https://api.openai.com/v1',anthropic:'https://api.anthropic.com/v1',gemini:'https://generativelanguage.googleapis.com/v1beta/openai',xai:'https://api.x.ai/v1',ollama:'http://127.0.0.1:11434/v1',compatible:'http://127.0.0.1:1234/v1'};
export interface ChatMessage {role:'system'|'user'|'assistant'|'tool';content:any;tool_call_id?:string;tool_calls?:any[];}
export interface ToolDefinition {type:'function';function:{name:string;description:string;parameters:Record<string,unknown>};}
export interface Generation {text:string;calls:{id:string;name:string;arguments:string}[];usage?:unknown;}
const textCaps:Capabilities={text:true,tools:false,vision:false,audioInput:false,audioOutput:false,imageGeneration:false};
export function validateEndpoint(value:string){const url=new URL(value);if(url.username||url.password)throw Error('Endpoint must not contain credentials');if(url.protocol!=='https:' && !(url.protocol==='http:' && ['localhost','127.0.0.1','[::1]'].includes(url.hostname)))throw Error('Use HTTPS, or HTTP for a loopback model server');return value.replace(/\/$/,'');}
async function request(profile:ProviderProfile,key:string,path:string,body?:unknown,signal?:AbortSignal){const base=validateEndpoint(profile.baseUrl);const headers:Record<string,string>={'Content-Type':'application/json'};if(profile.kind==='anthropic'){headers['x-api-key']=key;headers['anthropic-version']='2023-06-01';}else if(key)headers.Authorization=`Bearer ${key}`;if(profile.kind==='openrouter')headers['X-OpenRouter-Title']='Fox Bot';const r=await fetch(base+path,{method:body?'POST':'GET',headers,body:body?JSON.stringify(body):undefined,signal,redirect:'error'});if(!r.ok){const code=r.status===401?'Invalid provider credential':r.status===429?'Provider rate limit exceeded':`Provider request failed (${r.status})`;throw Error(code);}return r;}
export async function discover(profile:ProviderProfile,key:string):Promise<Model[]>{const r=await request(profile,key,'/models');const j:any=await r.json();return(j.data??[]).map((m:any)=>{const modalities=m.architecture?.input_modalities??[];const output=m.architecture?.output_modalities??[];const parameters=m.supported_parameters??[];return{id:m.id,name:m.name??m.display_name??m.id,contextLength:m.context_length,capabilitiesSource:Array.isArray(m.supported_parameters)||Array.isArray(m.architecture?.input_modalities)?'provider':profile.kind==='anthropic'?'adapter':'unknown',capabilities:{...textCaps,tools:parameters.includes('tools') || profile.kind==='anthropic',vision:modalities.includes('image'),audioInput:modalities.includes('audio'),audioOutput:output.includes('audio'),imageGeneration:output.includes('image')}};});}
export async function* sse(response:Response):AsyncGenerator<any>{if(!response.body)throw Error('Provider returned no stream');const reader=response.body.getReader();const decoder=new TextDecoder();let buffer='';try{while(true){const{done,value}=await reader.read();buffer+=done?decoder.decode():decoder.decode(value,{stream:true});buffer=buffer.replaceAll('\r\n','\n');let n;while((n=buffer.indexOf('\n\n'))>=0){const record=buffer.slice(0,n);buffer=buffer.slice(n+2);const data=record.split('\n').filter(l=>l.startsWith('data:')).map(l=>l.slice(5).trimStart()).join('\n');if(data==='[DONE]'){await reader.cancel();return;}if(data){let parsed;try{parsed=JSON.parse(data);}catch{throw Error('Invalid provider event');}yield parsed;}}if(done)break;}}finally{reader.releaseLock();}}
export async function generate(profile:ProviderProfile,key:string,model:string,messages:ChatMessage[],tools:ToolDefinition[],signal:AbortSignal,onText:(chunk:string)=>void):Promise<Generation>{
 if(!model.trim())throw Error('Select a model in this bot’s settings');
 if(profile.kind==='anthropic')return anthropic(profile,key,model,messages,tools,signal,onText);
 const response=await request(profile,key,'/chat/completions',{model,messages,stream:true,...(tools.length?{tools}:{}),...(profile.kind==='ollama'?{}:{stream_options:{include_usage:true}})},signal);
 let text='';const calls=new Map<number,{id:string;name:string;arguments:string}>();let usage:unknown;
 for await(const e of sse(response)){if(e.error)throw Error('Provider returned an error');usage=e.usage??usage;const d=e.choices?.[0]?.delta;if(d?.content){text+=d.content;onText(d.content);}for(const t of d?.tool_calls??[]){const c=calls.get(t.index)??{id:'',name:'',arguments:''};c.id=t.id??c.id;c.name+=t.function?.name??'';c.arguments+=t.function?.arguments??'';calls.set(t.index,c);}}
 return{text,calls:[...calls.values()],usage};
}
async function anthropic(profile:ProviderProfile,key:string,model:string,messages:ChatMessage[],tools:ToolDefinition[],signal:AbortSignal,onText:(s:string)=>void):Promise<Generation>{
 const system=messages.filter(m=>m.role==='system').map(m=>m.content).join('\n');const converted:any[]=[];
 for(const m of messages.filter(m=>m.role!=='system')){
  let item:any;if(m.role==='tool')item={role:'user',content:[{type:'tool_result',tool_use_id:m.tool_call_id,content:m.content}]};
  else if(m.tool_calls)item={role:'assistant',content:[...(m.content?[{type:'text',text:m.content}]:[]),...m.tool_calls.map(t=>({type:'tool_use',id:t.id,name:t.function.name,input:JSON.parse(t.function.arguments)}))]};
  else item={role:m.role,content:typeof m.content==='string'?m.content:m.content.map((c:any)=>c.type==='text'?{type:'text',text:c.text}:{type:'image',source:{type:'base64',media_type:c.image_url.url.split(';')[0].slice(5),data:c.image_url.url.split(',')[1]}})};
  const last=converted.at(-1);if(last?.role===item.role){last.content=[...(typeof last.content==='string'?[{type:'text',text:last.content}]:last.content),...(typeof item.content==='string'?[{type:'text',text:item.content}]:item.content)];}else converted.push(item);
 }
 const r=await request(profile,key,'/messages',{model,max_tokens:4096,system,messages:converted,stream:true,...(tools.length?{tools:tools.map(t=>({name:t.function.name,description:t.function.description,input_schema:t.function.parameters}))}:{})},signal);
 let text='';const calls=new Map<number,{id:string;name:string;arguments:string}>();const initial=new Map<number,any>();let usage:any={};
 for await(const e of sse(r)){if(e.type==='error')throw Error('Provider returned an error');if(e.type==='content_block_start' && e.content_block.type==='tool_use'){calls.set(e.index,{id:e.content_block.id,name:e.content_block.name,arguments:''});initial.set(e.index,e.content_block.input);}if(e.delta?.type==='text_delta'){text+=e.delta.text;onText(e.delta.text);}if(e.delta?.type==='input_json_delta'){const c=calls.get(e.index);if(c)c.arguments+=e.delta.partial_json;}usage={...usage,...e.message?.usage,...e.usage};}
 for(const[index,c]of calls)if(!c.arguments)c.arguments=JSON.stringify(initial.get(index)??{});
 return{text,calls:[...calls.values()].map(c=>({...c,arguments:c.arguments||'{}'})),usage};
}
