import {z} from 'zod';

export const SPEECH_LIMITS={inputBytes:25_000_000,outputBytes:32_000_000,transcriptBytes:2_000_000,textCharacters:4096,timeoutMs:120_000} as const;
export type SpeechKind='openai'|'xai'|'compatible'|'local';
export type SpeechFormat='mp3'|'wav'|'opus'|'aac'|'flac'|'pcm'|'mulaw'|'alaw';
export interface SpeechCapabilities {transcription:boolean;synthesis:boolean;inputFormats:string[];outputFormats:SpeechFormat[];streamingSynthesis:boolean;realtimeConversation:false;}
export const SPEECH_PROVIDERS:Record<'openai'|'xai', {baseUrl:string;transcriptionModel:string;synthesisModel:string;voice:string;capabilities:SpeechCapabilities}>={
 openai:{baseUrl:'https://api.openai.com/v1',transcriptionModel:'gpt-transcribe',synthesisModel:'gpt-4o-mini-tts',voice:'coral',capabilities:{transcription:true,synthesis:true,inputFormats:['mp3','mp4','mpeg','mpga','m4a','wav','webm'],outputFormats:['mp3','wav','opus','aac','flac','pcm'],streamingSynthesis:true,realtimeConversation:false}},
 xai:{baseUrl:'https://api.x.ai/v1',transcriptionModel:'grok-voice-transcribe-2.0',synthesisModel:'',voice:'eve',capabilities:{transcription:true,synthesis:true,inputFormats:['mp3','wav','webm','ogg','m4a'],outputFormats:['mp3','wav','pcm','mulaw','alaw'],streamingSynthesis:true,realtimeConversation:false}}
};
const profileSchema=z.object({id:z.string().min(1).max(100),kind:z.enum(['openai','xai','compatible','local']),baseUrl:z.string().url(),auth:z.enum(['bearer','none']).default('bearer'),transcriptionModel:z.string().min(1).max(200).optional(),synthesisModel:z.string().min(1).max(200).optional(),voice:z.string().min(1).max(100).optional(),capabilities:z.object({transcription:z.boolean(),synthesis:z.boolean(),inputFormats:z.array(z.enum(['mp3','mp4','mpeg','mpga','m4a','wav','webm','ogg','flac'])),outputFormats:z.array(z.enum(['mp3','wav','opus','aac','flac','pcm','mulaw','alaw']))}).optional()}).strict();
export type SpeechProfile=z.input<typeof profileSchema>;
export interface TranscriptionInput {bytes:Uint8Array;filename:string;mime:string;model?:string;language?:string;prompt?:string;}
export interface TranscriptionResult {text:string;language?:string;duration?:number;}
export interface SynthesisInput {text:string;model?:string;voice?:string;format?:SpeechFormat;language?:string;speed?:number;instructions?:string;}
export interface SpeechStream {mime:string;format:SpeechFormat;chunks:AsyncIterable<Uint8Array>;cancel:()=>Promise<void>;}
export interface SpeechResult {bytes:Uint8Array;mime:string;format:SpeechFormat;}
export interface SpeechDeps {credential:(profileId:string)=>Promise<string>;fetch?:typeof fetch;}
const inputMimes:Record<string,string[]>={mp3:['audio/mpeg','audio/mp3'],mpga:['audio/mpeg'],mpeg:['audio/mpeg','video/mpeg'],mp4:['audio/mp4','video/mp4'],m4a:['audio/mp4','audio/x-m4a'],wav:['audio/wav','audio/x-wav','audio/wave'],webm:['audio/webm','video/webm'],ogg:['audio/ogg','application/ogg'],flac:['audio/flac','audio/x-flac']};
const outputMimes:Record<SpeechFormat,string[]>={mp3:['audio/mpeg','audio/mp3'],wav:['audio/wav','audio/x-wav','audio/wave'],opus:['audio/ogg','audio/opus'],aac:['audio/aac'],flac:['audio/flac','audio/x-flac'],pcm:['audio/pcm','audio/L16','application/octet-stream'],mulaw:['audio/basic'],alaw:['audio/alaw']};
const cleanMime=(mime:string)=>mime.split(';')[0].trim().toLowerCase();
const language=z.string().regex(/^[a-zA-Z]{2,3}(?:-[a-zA-Z0-9]{2,8})*$/);
function endpoint(profile:SpeechProfile){const p=profileSchema.parse(profile),u=new URL(p.baseUrl);const loopback=['127.0.0.1','localhost','[::1]'].includes(u.hostname);if(u.username||u.password||u.search||u.hash)throw Error('Speech endpoint must not contain credentials, query or fragment');if(u.protocol!=='https:'&&!(u.protocol==='http:'&&loopback))throw Error('Speech endpoint requires HTTPS or loopback HTTP');if(p.kind==='local'&&!loopback)throw Error('Local speech requires a loopback endpoint');if((p.kind==='openai'||p.kind==='xai')&&p.auth==='none')throw Error('Cloud speech requires a credential');if((p.kind==='local'||p.kind==='compatible')&&!p.capabilities)throw Error('Compatible speech requires explicit capability declarations');return{...p,baseUrl:p.baseUrl.replace(/\/$/,'')};}
export function speechCapabilities(profile:SpeechProfile):SpeechCapabilities{const p=endpoint(profile);if(p.kind==='openai'||p.kind==='xai')return structuredClone(SPEECH_PROVIDERS[p.kind].capabilities);return{...p.capabilities!,streamingSynthesis:true,realtimeConversation:false};}
function audioInput(input:TranscriptionInput,capabilities:SpeechCapabilities){if(!(input.bytes instanceof Uint8Array)||!input.bytes.length||input.bytes.length>SPEECH_LIMITS.inputBytes)throw Error('Audio must contain 1–25,000,000 bytes');if(!/^[^/\\\r\n\0]{1,160}$/.test(input.filename))throw Error('Audio filename must be a simple basename');const extension=input.filename.split('.').pop()!.toLowerCase();if(!capabilities.inputFormats.includes(extension))throw Error('Audio format is not supported by this speech provider');if(!inputMimes[extension]?.includes(cleanMime(input.mime)))throw Error('Audio MIME type does not match its format');if(input.language)language.parse(input.language);if(input.prompt!==undefined)z.string().max(4000).parse(input.prompt);return extension;}
function checkSignature(bytes:Uint8Array,format:string){const b=Buffer.from(bytes);const head=b.subarray(0,16);if(format==='wav'&&!(head.toString('ascii',0,4)==='RIFF'&&head.toString('ascii',8,12)==='WAVE'))throw Error('Invalid WAV container');if(format==='webm'&&head.subarray(0,4).toString('hex')!=='1a45dfa3')throw Error('Invalid WebM container');if(format==='ogg'&&head.toString('ascii',0,4)!=='OggS')throw Error('Invalid Ogg container');if(format==='flac'&&head.toString('ascii',0,4)!=='fLaC')throw Error('Invalid FLAC container');if(['m4a','mp4'].includes(format)&&head.toString('ascii',4,8)!=='ftyp')throw Error('Invalid MP4 audio container');if(['mp3','mpga'].includes(format)&&!(head.toString('ascii',0,3)==='ID3'||(head[0]===0xff&&(head[1]&0xe0)===0xe0)))throw Error('Invalid MPEG audio container');}
async function* boundedBody(response:Response,signal:AbortSignal,limit:number):AsyncGenerator<Uint8Array>{if(!response.body)throw Error('Speech provider returned an empty body');const declared=Number(response.headers.get('content-length')??0);if(declared>limit){await response.body.cancel();throw Error('Speech response exceeds size limit');}const reader=response.body.getReader();let total=0;const abort=()=>{void reader.cancel().catch(()=>{});};signal.addEventListener('abort',abort,{once:true});try{while(true){signal.throwIfAborted();const {done,value}=await reader.read();signal.throwIfAborted();if(done)break;total+=value.length;if(total>limit)throw Error('Speech response exceeds size limit');if(value.length)yield value;}if(!total)throw Error('Speech provider returned empty audio');}catch(e){if(signal.aborted)signal.throwIfAborted();if(e instanceof Error&&/size limit|empty/.test(e.message))throw e;throw Error('Speech response stream failed');}finally{signal.removeEventListener('abort',abort);await reader.cancel().catch(()=>{});reader.releaseLock();}}
async function collect(body:AsyncIterable<Uint8Array>){const chunks=[];for await(const chunk of body)chunks.push(chunk);return new Uint8Array(Buffer.concat(chunks));}

export class SpeechAdapter{
 constructor(readonly deps:SpeechDeps){}
 private async request(profile:SpeechProfile,path:string,body:BodyInit,json:boolean,signal:AbortSignal){const p=endpoint(profile);signal.throwIfAborted();const key=p.auth==='none'?'':await this.deps.credential(p.id);if(p.auth!=='none'&&!key)throw Error('Speech credential is missing');const linked=AbortSignal.any([signal,AbortSignal.timeout(SPEECH_LIMITS.timeoutMs)]);try{const response=await(this.deps.fetch??fetch)(p.baseUrl+path,{method:'POST',headers:{...(key?{Authorization:`Bearer ${key}`}:{ }),...(json?{'Content-Type':'application/json'}:{})},body,redirect:'error',signal:linked});if(!response.ok){await response.body?.cancel();throw Error(`Speech request failed (HTTP ${response.status})`);}return{response,signal:linked,key};}catch(e){linked.throwIfAborted();if(e instanceof Error&&/^Speech request failed \(HTTP \d+\)$/.test(e.message))throw e;throw Error('Speech network request failed');}}
 async transcribe(profile:SpeechProfile,input:TranscriptionInput,signal:AbortSignal):Promise<TranscriptionResult>{const p=endpoint(profile),caps=speechCapabilities(profile);if(!caps.transcription)throw Error('Transcription is not enabled for this speech provider');const extension=audioInput(input,caps);checkSignature(input.bytes,extension);const defaults=p.kind==='openai'||p.kind==='xai'?SPEECH_PROVIDERS[p.kind]:undefined;const model=z.string().min(1).max(200).parse(input.model??p.transcriptionModel??defaults?.transcriptionModel);const form=new FormData();form.append('model',model);if(p.kind!=='xai')form.append('response_format','json');if(input.language)form.append('language',input.language);if(input.prompt){if(p.kind==='xai')throw Error('xAI transcription prompting requires keyterms and is not exposed by this adapter');form.append('prompt',input.prompt);}form.append('file',new Blob([new Uint8Array(input.bytes)],{type:cleanMime(input.mime)}),input.filename);const {response,signal:linked,key}=await this.request(p,p.kind==='xai'?'/stt':'/audio/transcriptions',form,false,signal);if(cleanMime(response.headers.get('content-type')??'')!=='application/json'){await response.body?.cancel();throw Error('Transcription response must be JSON');}const bytes=await collect(boundedBody(response,linked,SPEECH_LIMITS.transcriptBytes));let data:any;try{data=JSON.parse(Buffer.from(bytes).toString('utf8'));}catch{throw Error('Transcription response is invalid JSON');}if(typeof data.text!=='string'||data.text.length>200000)throw Error('Transcription response has no valid text');return{text:key?data.text.split(key).join('[redacted]'):data.text,...(typeof data.language==='string'?{language:data.language}:{}),...(typeof data.duration==='number'&&Number.isFinite(data.duration)&&data.duration>=0?{duration:data.duration}:{})};}
 async synthesizeStream(profile:SpeechProfile,input:SynthesisInput,signal:AbortSignal):Promise<SpeechStream>{const p=endpoint(profile),caps=speechCapabilities(profile);if(!caps.synthesis)throw Error('Synthesis is not enabled for this speech provider');z.string().min(1).max(SPEECH_LIMITS.textCharacters).parse(input.text);const format=input.format??'mp3';if(!caps.outputFormats.includes(format))throw Error('Speech output format is not supported');if(input.language&&input.language!=='auto')language.parse(input.language);if(input.speed!==undefined)z.number().min(0.25).max(4).parse(input.speed);if(input.instructions!==undefined)z.string().max(2000).parse(input.instructions);const defaults=p.kind==='openai'||p.kind==='xai'?SPEECH_PROVIDERS[p.kind]:undefined;const voice=z.string().min(1).max(100).parse(input.voice??p.voice??defaults?.voice);let body:Record<string,unknown>;
  if(p.kind==='xai'){if(input.instructions)throw Error('xAI voice instructions are not exposed by this adapter');body={text:input.text,voice_id:voice,language:input.language??'auto',output_format:{codec:format},...(input.speed!==undefined?{speed:input.speed}:{})};}
  else{const model=z.string().min(1).max(200).parse(input.model??p.synthesisModel??defaults?.synthesisModel);body={model,input:input.text,voice,response_format:format,...(input.speed!==undefined?{speed:input.speed}:{}),...(input.instructions?{instructions:input.instructions}:{})};}
  const controller=new AbortController(),linked=AbortSignal.any([signal,controller.signal]);const {response,signal:requestSignal}=await this.request(p,p.kind==='xai'?'/tts':'/audio/speech',JSON.stringify(body),true,linked);const mime=cleanMime(response.headers.get('content-type')??'');const allowed=outputMimes[format].map(cleanMime);if(!allowed.includes(mime)&&mime!=='application/octet-stream'){await response.body?.cancel();throw Error('Speech response MIME does not match requested audio format');}return{mime:allowed[0],format,chunks:boundedBody(response,requestSignal,SPEECH_LIMITS.outputBytes),cancel:async()=>{controller.abort();if(response.body&&!response.body.locked)await response.body.cancel().catch(()=>{});}};
 }
 async synthesize(profile:SpeechProfile,input:SynthesisInput,signal:AbortSignal):Promise<SpeechResult>{const stream=await this.synthesizeStream(profile,input,signal);try{return{bytes:await collect(stream.chunks),mime:stream.mime,format:stream.format};}finally{await stream.cancel();}}
}
