import {useEffect,useState} from 'react';
type Catalog={kind:string;name:string;scopes:string[];tools:{name:string;description:string;scopes:string[];approval:boolean}[]};
type Connection={id:string;name:string;kind:string;enabled:boolean;grantedScopes:string[]};
export function ConnectorPanel(){
 const [catalog,setCatalog]=useState<Catalog[]>([]),[connections,setConnections]=useState<Connection[]>([]),[kind,setKind]=useState('github'),[name,setName]=useState(''),[key,setKey]=useState(''),[scopes,setScopes]=useState<string[]>([]),[manifest,setManifest]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const request=async(type:string,payload:Record<string,unknown>={})=>{const r=await window.fox.command(type,payload);if(!r.ok)throw Error(r.error?.message??'Connector request failed');return r.data;};
 const reload=async()=>{const [c,s]=await Promise.all([request('connector.catalog'),request('connector.list')]);setCatalog(c);setConnections(s);};
 useEffect(()=>{void reload().catch(e=>setError(e.message));},[]);
 const selected=catalog.find(c=>c.kind===kind);
 const submit=async()=>{setBusy(true);setError('');try{const config=kind==='manifest'?JSON.parse(manifest):{id:crypto.randomUUID(),kind,name:name||selected?.name,enabled:true,grantedScopes:scopes};const r=await window.fox.desktop('connector.save',{manifest:config,key});if(!r.ok)throw Error(r.error?.message??'Connection failed');setKey('');setName('');await reload();}catch(e){setError(e instanceof Error?e.message:'Invalid connector configuration');}finally{setBusy(false);}};
 const remove=async(id:string)=>{setError('');try{const r=await window.fox.desktop('connector.remove',{id});if(!r.ok)throw Error(r.error?.message??'Removal failed');await reload();}catch(e){setError(e instanceof Error?e.message:'Removal failed');}};
 return <section aria-label="Service connections"><div className="section-heading">Service connections</div><p className="muted">Connect each service separately with a token you authorized for the permissions below. Tokens stay in the PC’s secure storage. Service OAuth setup remains a separate step.</p>{connections.map(c=><div className="list-row" key={c.id}><div><strong>{c.name}</strong><p>{c.kind} · {c.enabled?'Enabled':'Disabled'}</p><small>{c.grantedScopes.join(', ')||'No declared scopes'}</small></div><button disabled={busy} onClick={()=>void remove(c.id)}>Disconnect</button></div>)}<form onSubmit={e=>{e.preventDefault();void submit();}}><label>Service<select value={kind} onChange={e=>{setKind(e.target.value);setScopes([]);}}>{catalog.map(c=><option key={c.kind} value={c.kind}>{c.name}</option>)}<option value="manifest">HTTP or MCP manifest</option></select></label>{kind==='manifest'?<label>Connector manifest JSON<textarea required rows={7} value={manifest} onChange={e=>setManifest(e.target.value)} placeholder={'{"id":"my-tools","name":"My tools","kind":"mcp","url":"https://example.com/mcp","grantedScopes":[],"readOnlyTools":[],"auth":"bearer"}'}/></label>:<><label>Connection name<input value={name} onChange={e=>setName(e.target.value)} placeholder={selected?.name}/></label><p className="muted">Select only scopes granted by this token. Fox Bot restricts tools using this selection; it cannot expand the token’s service permissions.</p>{selected?.scopes.map(scope=><label key={scope} className="checkbox"><input type="checkbox" checked={scopes.includes(scope)} onChange={e=>setScopes(old=>e.target.checked?[...old,scope]:old.filter(s=>s!==scope))}/>{scope}</label>)}<details><summary>Available tools</summary>{selected?.tools.map(t=><p key={t.name}><strong>{t.name}</strong> — {t.description}{t.approval?' · owner approval required':''}</p>)}</details></>}<label>Access token<input type="password" autoComplete="off" value={key} onChange={e=>setKey(e.target.value)}/></label><button className="primary" disabled={busy}>{busy?'Connecting…':'Connect service'}</button>{error&&<p role="alert" className="error">{error}</p>}</form></section>;
}
