import React,{useState,useEffect,useRef} from 'react';
import {createRoot} from 'react-dom/client';
import {Plus,Search,Settings,ChevronDown,ArrowUp,Paperclip,Mic,Square,Monitor,Clock,BookOpen,Users,MoreHorizontal,X,Check,Shield,FolderOpen,Smartphone,Pin,EyeOff,Copy,Trash2,Download,Upload,Link,Activity,ArrowRight,LoaderCircle} from 'lucide-react';
import Markdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import remarkMath from 'remark-math';
import rehypeKatex from 'rehype-katex';
import 'katex/dist/katex.min.css';
import './style.css';
import type {Snapshot,Bot,ProviderProfile,Attachment} from '@foxbot/protocol';
import {startRemote} from './remote';
import {MemoryEditor} from './MemoryEditor';
import {ConnectorPanel} from './ConnectorPanel';
import {VoicePanel} from './VoicePanel';
const fox=window.fox;
const blank:Snapshot={version:1,seq:0,bots:[],conversations:[],messages:[],runs:[],tools:[],approvals:[],providers:[],skills:[],routines:[],memories:[],artifacts:[],devices:[]};
function FoxMark({size=28}:{size?:number}){return <svg width={size} height={size} viewBox="0 0 48 48" fill="none" aria-label="Fox Bot"><path d="M8 7 20 14H28L40 7 38 28 24 42 10 28Z" fill="currentColor"/><path d="m15 24 6 3-3 5-5-5Zm18 0-6 3 3 5 5-5Z" fill="#080808"/><path d="m21 35 3-4 3 4-3 2Z" fill="#080808"/></svg>;}
function App(){
 const[s,setS]=useState(blank),[current,setCurrent]=useState(''),[panel,setPanel]=useState(''),[editing,setEditing]=useState<Bot|null>(null),[text,setText]=useState(''),[error,setError]=useState(''),[status,setStatus]=useState<any>(null),[welcome,setWelcome]=useState(localStorage.getItem('fox.localWorkspace')!=='yes'),[attachments,setAttachments]=useState<Attachment[]>([]),[search,setSearch]=useState(''),[results,setResults]=useState<any[]>([]),[pair,setPair]=useState<any>(null),[remoteRequest,setRemoteRequest]=useState<any>(null),[sidebar,setSidebar]=useState(true),[busy,setBusy]=useState(false);
 const bottom=useRef<HTMLDivElement>(null),input=useRef<HTMLTextAreaElement>(null);
 const conv=s.conversations.find(c=>c.id===current),bot=s.bots.find(b=>b.id===conv?.botIds[0]);
 const active=s.runs.filter(r=>r.conversationId===current&&!['completed','failed','cancelled'].includes(r.status));
 const ask=async(type:string,payload:any={})=>{const r=await fox.command(type,payload);if(!r.ok)throw Error(r.error?.message??'Request failed');return r.data;};
 const desktop=async(type:string,payload:any={})=>{const r=await fox.desktop(type,payload);if(!r.ok)throw Error(r.error?.message??'Request failed');return r.data;};
 const refresh=async()=>{const data=await ask('snapshot');setS(data);setCurrent(old=>data.conversations.some((c:any)=>c.id===old)?old:data.conversations[0]?.id??'');};
 const action=async(fn:()=>Promise<any>)=>{setError('');try{await fn();await refresh();}catch(e:any){setError(e.message);}};
 useEffect(()=>{
  let mounted=true,timer:ReturnType<typeof setTimeout>|undefined,inFlight=false,dirty=false;
  const update=async()=>{if(inFlight){dirty=true;return;}inFlight=true;try{const data=await ask('snapshot');if(mounted){setS(data);setCurrent(old=>data.conversations.some((c:any)=>c.id===old)?old:data.conversations[0]?.id??'');}}catch(e){if(mounted)setError(e instanceof Error?e.message:'Could not refresh');}finally{inFlight=false;if(dirty&&mounted){dirty=false;schedule();}}};
  const schedule=()=>{if(!timer)timer=setTimeout(()=>{timer=undefined;void update();},100);};
  void Promise.all([update(),desktop('status').then(value=>{if(mounted)setStatus(value);})]).catch(e=>{if(mounted)setError(e.message);});
  const unsub=fox.onEvent(schedule),off=fox.onRemote((m:any)=>{if(m.type==='pair_request')setRemoteRequest(m);if(m.type==='error')setError(m.message);});
  return()=>{mounted=false;unsub();off();clearTimeout(timer);};
 },[]);
 useEffect(()=>{setText(conv?.draft??'');setAttachments([]);},[current]);
 useEffect(()=>{bottom.current?.scrollIntoView({behavior:'smooth'});},[s.messages.length,s.messages.at(-1)?.content,current]);
 useEffect(()=>{const handle=(e:KeyboardEvent)=>{if(e.ctrlKey && e.key.toLowerCase()==='k'){e.preventDefault();setPanel('search');}if(e.ctrlKey && e.key.toLowerCase()==='n'){e.preventDefault();setEditing(null);setPanel('profile');}if(e.ctrlKey&&e.key.toLowerCase()==='b'){e.preventDefault();setSidebar(x=>!x);}if(e.ctrlKey&&e.key===','){e.preventDefault();setPanel('settings');}if(e.key==='Escape'){setPanel('');setRemoteRequest(null);}};window.addEventListener('keydown',handle);return()=>window.removeEventListener('keydown',handle);},[]);
 const send=async()=>{if(!text.trim()||!conv)return;const value=text;setText('');setAttachments([]);await action(async()=>{await ask('message.send',{conversationId:conv.id,content:value,attachments});});};
 const selectBot=(b:Bot)=>{const c=s.conversations.find(c=>!c.group&&c.botIds[0]===b.id);if(c)setCurrent(c.id);setPanel('');};
 if(welcome)return <div className="welcome"><div className="welcome-brand"><FoxMark size={62}/><h1>Fox Bot</h1></div><p>Your team of local Bots that<br/>you can give real work to</p><button className="signin" disabled={!status?.chatgptAvailable||busy} onClick={()=>void action(async()=>{setBusy(true);try{await desktop('auth.chatgpt');setWelcome(false);}finally{setBusy(false);}})}>{busy?<LoaderCircle size={16}/>:null} Sign in with ChatGPT <ArrowRight size={16}/></button>{!status?.chatgptAvailable&&<small>Official ChatGPT sign-in registration is required.</small>}<button className="local-link" onClick={()=>{localStorage.setItem('fox.localWorkspace','yes');setWelcome(false);}}>Open local development workspace</button>{error&&<p className="error">{error}</p>}<footer>Fox Bot is open source. AI provider accounts connect separately.</footer></div>;
 return <div className={'app '+(!sidebar?'collapsed':'')}>
 {sidebar&&<aside><div className="brand"><FoxMark/><span>Fox Bot</span><button className="icon" title="New bot" onClick={()=>{setEditing(null);setPanel('profile');}}><Plus size={19}/></button></div><button className="search-button" onClick={()=>setPanel('search')}><Search size={16}/> Search <kbd>Ctrl K</kbd></button><div className="sidebar-label">Your Bots <button className="icon" onClick={()=>{setEditing(null);setPanel('profile');}}><Plus size={15}/></button></div><div className="roster">{s.bots.filter(b=>!b.hidden).sort((a,b)=>Number(b.pinned)-Number(a.pinned)).map(b=><button key={b.id} className={'bot-row '+(b.id===bot?.id&&!conv?.group?'selected':'')} onClick={()=>selectBot(b)}><span className="avatar">{b.avatar==='fox'?<FoxMark size={20}/>:b.name[0]}</span><span>{b.name}</span>{s.runs.some(r=>r.botId===b.id&&r.status==='running')&&<span className="live-dot"/>}{b.pinned&&<Pin size={12}/>}</button>)}{s.conversations.filter(c=>c.group).map(c=><button key={c.id} className={'bot-row '+(c.id===current?'selected':'')} onClick={()=>setCurrent(c.id)}><span className="avatar"><Users size={18}/></span><span>{c.title}</span></button>)}</div><button className="sidebar-action" onClick={()=>setPanel('groups')}><Users size={16}/> New group chat</button><div className="sidebar-bottom"><button onClick={()=>setPanel('skills')}><BookOpen size={16}/> Skills & connectors</button><button onClick={()=>setPanel('routines')}><Clock size={16}/> Routines</button><button onClick={()=>setPanel('devices')}><Smartphone size={16}/> Connect phone</button><button onClick={()=>setPanel('settings')}><Settings size={16}/> Settings</button><div className="local-status"><span className="live-dot"/> Running on this computer</div></div></aside>}
 <main><header><div className="chat-heading"><span className="avatar">{conv?.group?<Users size={19}/>:<FoxMark size={20}/>}</span><div><strong>{conv?.title??'Fox Bot'}</strong><span>{conv?.group?`${conv.botIds.length} Bots`:bot?.role??'Local AI teammates'}</span></div></div><div className="header-actions"><button onClick={()=>setPanel('computer')} title="Computer"><Monitor size={18}/><span>Computer</span></button><button className="icon" title="Bot profile" onClick={()=>{setEditing(bot??null);setPanel('profile');}}><MoreHorizontal size={20}/></button></div></header>
 {error&&<div className="error-banner"><Shield size={16}/><span>{error}</span><button className="icon" onClick={()=>setError('')}><X size={16}/></button></div>}
 <div className="messages">{!s.messages.some(m=>m.conversationId===current)?<div className="empty-chat"><span className="large-avatar"><FoxMark size={42}/></span><h2>Meet {bot?.name??'your teammate'}</h2><p>Give your Bot a task, a little context,<br/>and access to the tools it needs.</p><div className="suggestions">{['Research a topic and write a brief','Organize files in my workspace','Create a reusable workflow'].map(t=><button key={t} onClick={()=>{setText(t);input.current?.focus();}}>{t}<ArrowRight size={14}/></button>)}</div>{!bot?.providerId&&<button className="primary" onClick={()=>setPanel('settings')}><Link size={15}/> Connect an AI provider</button>}</div>:s.messages.filter(m=>m.conversationId===current).map(m=><article key={m.id} className={'message '+m.role}><div className="message-name">{m.role==='assistant'?<FoxMark size={18}/>:<span className="you-avatar">Y</span>}<strong>{m.role==='assistant'?(s.bots.find(b=>b.id===m.botId)?.name??'Bot'):'You'}</strong><time>{new Date(m.createdAt).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</time><button className="icon message-reaction" title="React" onClick={()=>void action(()=>ask('message.react',{id:m.id,reaction:'👍'}))}><Check size={14}/></button></div><div className="message-body"><Markdown remarkPlugins={[remarkGfm,remarkMath]} rehypePlugins={[rehypeKatex]}>{m.content||'Thinking…'}</Markdown>{m.attachments.map(a=><span className="attachment-chip" key={a.id}><Paperclip size={12}/>{a.name}</span>)}{Object.entries(m.reactions).filter(([,n])=>n>0).map(([r,n])=><span className="reaction" key={r}>{r} {n}</span>)}</div></article>)}
 {s.tools.filter(t=>s.runs.some(r=>r.id===t.runId&&r.conversationId===current)).slice(-8).map(t=><details className="tool-card" key={t.id}><summary><Activity size={14}/>{t.name}<span>{t.status}</span></summary><pre>{t.output||JSON.stringify(t.args,null,2)}</pre></details>)}
 {s.approvals.filter(a=>a.status==='pending'&&s.runs.some(r=>r.id===a.runId&&r.conversationId===current)).map(a=><div className="approval-card" key={a.id}><div><Shield size={18}/><strong>Review this action</strong></div><pre>{a.summary}</pre><button className="primary" onClick={()=>void action(()=>ask('approval.resolve',{id:a.id,approved:true}))}>Approve</button><button onClick={()=>void action(()=>ask('approval.resolve',{id:a.id,approved:false}))}>Reject</button></div>)}
 {s.runs.filter(r=>r.conversationId===current&&r.status==='failed').slice(-1).map(r=><div key={r.id} className="run-error">{r.error}</div>)}<div ref={bottom}/></div>
 <div className="composer-wrap">{active.length>0&&<div className="run-status"><span className="live-dot"/>{active[0].status.replaceAll('_',' ')}<button onClick={()=>void action(()=>ask('run.cancel',{id:active[0].id}))}><Square size={12}/> Stop</button></div>}<div className="composer">{attachments.length>0&&<div className="attachment-list">{attachments.map(a=><button key={a.id} onClick={()=>setAttachments(x=>x.filter(b=>b.id!==a.id))}>{a.name}<X size={12}/></button>)}</div>}<textarea ref={input} value={text} placeholder={`Message ${bot?.name??'your Bots'}…`} onChange={e=>{const value=e.target.value;setText(value);if(conv)void ask('draft.save',{conversationId:conv.id,text:value}).catch(()=>{});}} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();void send();}}}/><div className="composer-tools"><button className="icon" title="Attach files" onClick={()=>void action(async()=>setAttachments(await desktop('attachment.pick')))}><Paperclip size={19}/></button><button className="icon" title="Insert skill" onClick={()=>setPanel('skills')}><BookOpen size={18}/></button><button className="icon" title="Voice" onClick={()=>setPanel('voice')}><Mic size={18}/></button><button className="model-label" onClick={()=>{setEditing(bot??null);setPanel('profile');}}>{bot?.model||'Select model'}<ChevronDown size={12}/></button><button className="send" aria-label="Send message" disabled={!text.trim()} onClick={()=>void send()}><ArrowUp size={19}/></button></div></div><p className="composer-note">Bots work on your PC. Review consequential actions before approving.</p></div></main>
 {panel&&<div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setPanel('');}}><section className={'modal '+(['settings','devices','computer'].includes(panel)?'wide':'')}><div className="modal-heading"><h2>{{profile:editing?'Edit Bot':'Create new Bot',settings:'Settings',skills:'Skills & connectors',routines:'Routines',groups:'New group chat',devices:'Connect your phone',computer:'Agent computer',search:'Search',voice:'Voice'}[panel]}</h2><button className="icon" onClick={()=>setPanel('')}><X size={20}/></button></div>
 {panel==='profile'&&<BotForm key={editing?.id??'new'} bot={editing} providers={s.providers} models={p=>ask('provider.models',{id:p})} save={v=>action(async()=>{await ask(editing?'bot.update':'bot.create',editing?{...v,id:editing.id,revision:editing.revision}:v);setPanel('');})} extra={editing?<div className="profile-actions"><button onClick={()=>void action(()=>ask('bot.duplicate',{id:editing.id}))}><Copy size={14}/>Duplicate</button><button onClick={()=>void action(()=>desktop('template.export',{id:editing.id}))}><Download size={14}/>Export</button><button onClick={()=>void action(async()=>{await ask('bot.update',{id:editing.id,revision:editing.revision,hidden:!editing.hidden});setPanel('');})}><EyeOff size={14}/>Hide</button><button className="danger" onClick={()=>{if(confirm('Delete this Bot, its conversations, memories, and routines? Shared files remain.'))void action(async()=>{await ask('bot.delete',{id:editing.id});setPanel('');});}}><Trash2 size={14}/>Delete</button></div>:null}/>} 
 {panel==='settings'&&<><p className="muted">Connect your model accounts. Keys stay in your computer’s secure storage.</p><ProviderForm save={v=>action(()=>desktop('provider.save',v))} openrouter={()=>action(()=>desktop('provider.openrouter'))}/>{s.providers.map(p=><div className="list-row" key={p.id}><div><strong>{p.name}</strong><p>{p.baseUrl}</p></div><span className="badge">{p.hasCredential?'Key saved':'Local / no key'}</span></div>)}<div className="section-heading">Account & workspace</div><p className="muted">{status?.identity?`Signed in as ${status.identity.name??status.identity.subject}`:'Official ChatGPT sign-in is unavailable until client registration is configured.'}</p><button disabled={!status?.chatgptAvailable} onClick={()=>void action(()=>desktop('auth.chatgpt'))}>Sign in with ChatGPT</button><button onClick={()=>void action(()=>desktop('workspace.open'))}><FolderOpen size={15}/>Open workspace</button><button onClick={()=>void action(()=>desktop('template.import'))}><Upload size={15}/>Import Bot template</button><div className="section-heading">Hidden Bots</div>{s.bots.filter(b=>b.hidden).map(b=><button key={b.id} onClick={()=>void action(()=>ask('bot.update',{id:b.id,revision:b.revision,hidden:false}))}>Show {b.name}</button>)}<p className="muted">Fox Bot {status?.version} · secure storage {status?.secureStorage?'available':'unavailable'}</p></>}
 {panel==='skills'&&<><p className="muted">Reusable instructions for your Bots. Select one to insert it into your message.</p>{s.skills.map(k=><div className="list-row" key={k.id}><div><strong>{k.name}</strong><p>{k.description}</p></div><button onClick={()=>{setText(t=>t+` /${k.name}`);setPanel('');}}>Use</button><button className="icon" onClick={()=>void action(()=>ask('skill.delete',{id:k.id}))}><Trash2 size={15}/></button></div>)}<SkillForm save={v=>action(()=>ask('skill.save',v))}/><div className="section-heading">Connected tools</div><p className="muted">Browser, workspace files, and terminal tools are built in. Additional service connections require their own credentials and permissions.</p></>}
 {panel==='routines'&&<>{s.routines.map(r=><div className="list-row" key={r.id}><div><strong>{r.name}</strong><p>{r.cron} · {r.timezone}<br/>Next: {new Date(r.nextRun).toLocaleString()}</p></div><button onClick={()=>void action(()=>ask('routine.save',{...r,enabled:!r.enabled}))}>{r.enabled?'Pause':'Enable'}</button><button onClick={()=>void action(()=>ask('routine.test',{id:r.id}))}>Test</button><button className="icon" onClick={()=>void action(()=>ask('routine.delete',{id:r.id}))}><Trash2 size={15}/></button></div>)}<RoutineForm bots={s.bots} save={v=>action(()=>ask('routine.save',v))}/><p className="muted">The PC must be running. Missed runs are reported and skipped.</p></>}
 {panel==='settings'&&<MemoryEditor bots={s.bots} memories={s.memories} save={async v=>{await ask('memory.save',v);await refresh();}} remove={id=>action(()=>ask('memory.delete',{id}))}/>}
 {panel==='skills'&&<ConnectorPanel/>}
 {panel==='groups'&&<GroupForm bots={s.bots} save={v=>action(async()=>{const c=await ask('conversation.create',v);setCurrent(c.id);setPanel('');})}/>}
 {panel==='computer'&&<button onClick={()=>void action(()=>ask('emergency.resume',{}))}>Resume computer automation after emergency stop</button>}
 {panel==='search'&&<><div className="search-input"><Search size={18}/><input autoFocus value={search} placeholder="Search messages, Bots, and skills" onChange={e=>{setSearch(e.target.value);void ask('search',{text:e.target.value}).then(setResults).catch((e:any)=>setError(e.message));}}/></div>{results.map(r=><button className="search-result" key={r.id} onClick={()=>{if(r.collection==='bots')selectBot(s.bots.find(b=>b.id===r.id)!);else if(r.collection==='messages'){setCurrent(s.messages.find(m=>m.id===r.id)?.conversationId??current);setPanel('');}}}><span className="badge">{r.collection}</span>{r.text.slice(0,160)}</button>)}</>}
 {panel==='devices'&&<><p className="muted">Install the Android APK, configure your self-hosted relay, then scan a one-time pairing QR. Your PC runs every task.</p><RelayForm save={v=>action(async()=>{await desktop('remote.configure',v);setStatus(await desktop('status'));})}/><button className="primary" onClick={()=>void action(async()=>setPair(await desktop('remote.pairing')))}><Smartphone size={16}/>Generate pairing QR</button>{pair&&<div className="qr"><img src={pair.qr} alt="One-time phone pairing QR"/><p>Expires {new Date(pair.offer.expiresAt).toLocaleTimeString()}</p></div>}<button onClick={()=>void action(async()=>setStatus({...status,remote:await desktop('remote.status')}))}>Refresh devices</button>{status?.remote?.devices?.map((d:any)=><div className="list-row" key={d.id}><div>{d.name}<p>{d.revoked?'Revoked':'Paired'}</p></div><button disabled={d.revoked} onClick={()=>void action(()=>desktop('remote.revoke',{id:d.id}))}>Revoke</button></div>)}</>}
 {panel==='computer'&&<><p className="muted">Bots use dedicated browser windows and the shared workspace. Human takeover pauses native computer automation; dedicated browsers remain independent.</p><button onClick={()=>void action(()=>ask('computer.takeover',{enabled:true}))}>Take control</button><button onClick={()=>void action(()=>ask('computer.takeover',{enabled:false}))}>Return control to Bots</button><button onClick={()=>void action(()=>desktop('workspace.open'))}><FolderOpen size={16}/>Open workspace</button><button className="danger" onClick={()=>void action(()=>ask('emergency.stop',{}))}><Square size={14}/>Emergency stop all Bots</button><div className="section-heading">Files and results</div>{s.artifacts.map(a=><button className="search-result" key={a.id} onClick={()=>void action(()=>desktop('artifact.open',{id:a.id}))}><Download size={15}/>{a.name}<span className="muted">{Math.round(a.size/1024)} KB</span></button>)}</>}
 {panel==='voice'&&<VoicePanel providers={s.providers} defaultProviderId={bot?.providerId} onSend={v=>{setText(v);setPanel('');}} onError={setError}/>}
 </section></div>}
 {remoteRequest&&<div className="modal-backdrop"><section className="modal"><div className="modal-heading"><h2>Pair {remoteRequest.name}</h2></div><p>Compare this code with the one on your phone before approving.</p><div className="verification-code">{remoteRequest.code}</div><button className="primary" onClick={()=>void action(async()=>{await desktop('remote.approve',{peerId:remoteRequest.peerId,approved:true});setRemoteRequest(null);setPair(null);})}>Codes match — pair device</button><button onClick={()=>void action(async()=>{await desktop('remote.approve',{peerId:remoteRequest.peerId,approved:false});setRemoteRequest(null);})}>Reject</button></section></div>}
 </div>;
}
function BotForm({bot,providers,models,save,extra}:{bot:Bot|null;providers:ProviderProfile[];models:(p:string)=>Promise<any>;save:(v:any)=>void;extra:React.ReactNode}){const[v,set]=useState<any>(bot??{name:'',avatar:'fox',role:'',instructions:'',providerId:'',model:'',pinned:false,hidden:false});const[list,setList]=useState<any[]>([]);const[error,setError]=useState('');const field=(name:string,value:any)=>set((old:any)=>({...old,[name]:value}));return <form onSubmit={e=>{e.preventDefault();save(v);}}><label>Name<input autoFocus required maxLength={100} value={v.name} onChange={e=>field('name',e.target.value)}/></label><label>Primary job<input value={v.role} onChange={e=>field('role',e.target.value)} placeholder="Research, operations, coding…"/></label><label>Instructions<textarea rows={5} value={v.instructions} onChange={e=>field('instructions',e.target.value)} placeholder="Describe how this Bot should work and when it should ask you."/></label><div className="form-grid"><label>Provider<select value={v.providerId} onChange={e=>{field('providerId',e.target.value);field('model','');}}><option value="">Choose provider</option>{providers.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Model<input required={!!v.providerId} list="models" value={v.model} onChange={e=>field('model',e.target.value)} placeholder="Provider model ID"/><datalist id="models">{list.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</datalist></label></div><button type="button" disabled={!v.providerId} onClick={()=>void models(v.providerId).then(setList).catch((e:any)=>setError(e.message))}>Fetch available models</button>{error&&<p className="error">{error}</p>}<label className="checkbox"><input type="checkbox" checked={v.pinned} onChange={e=>field('pinned',e.target.checked)}/>Pin in sidebar</label><button className="primary" type="submit">{bot?'Save Bot':'Create Bot'}</button>{extra}</form>;}
function ProviderForm({save,openrouter}:{save:(v:any)=>void;openrouter:()=>void}){const[kind,setKind]=useState('openrouter'),[name,setName]=useState('OpenRouter'),[url,setUrl]=useState(''),[key,setKey]=useState('');return <form onSubmit={e=>{e.preventDefault();save({kind,name,...(url?{baseUrl:url}:{}),key});setKey('');}}><div className="form-grid"><label>Provider<select value={kind} onChange={e=>{setKind(e.target.value);setName(e.target.options[e.target.selectedIndex].text);}}>{['OpenRouter','OpenAI','Anthropic','Gemini','xAI','Compatible','Ollama'].map(p=><option value={p.toLowerCase()} key={p}>{p}</option>)}</select></label><label>Connection name<input required value={name} onChange={e=>setName(e.target.value)}/></label></div><label>API key<input type="password" autoComplete="off" value={key} onChange={e=>setKey(e.target.value)} placeholder={['ollama','compatible'].includes(kind)?'Optional for local servers':'Your provider API key'}/></label><label>Endpoint override<input value={url} onChange={e=>setUrl(e.target.value)} placeholder="Leave empty for the provider’s official endpoint"/></label><button className="primary">Save connection</button><button type="button" onClick={openrouter}>Connect with OpenRouter</button></form>;}
function SkillForm({save}:{save:(v:any)=>void}){const[name,setName]=useState(''),[markdown,setMarkdown]=useState('');return <form onSubmit={e=>{e.preventDefault();save({name,description:'',markdown});setName('');setMarkdown('');}}><div className="section-heading">Create a skill</div><label>Name<input required value={name} onChange={e=>setName(e.target.value)}/></label><label>Instructions<textarea required rows={4} value={markdown} onChange={e=>setMarkdown(e.target.value)}/></label><button className="primary">Save skill</button></form>;}
function RoutineForm({bots,save}:{bots:Bot[];save:(v:any)=>void}){const[botId,setBotId]=useState(bots[0]?.id??''),[name,setName]=useState(''),[prompt,setPrompt]=useState(''),[cron,setCron]=useState('0 8 * * 1-5'),[timezone,setTimezone]=useState(Intl.DateTimeFormat().resolvedOptions().timeZone);return <form onSubmit={e=>{e.preventDefault();save({botId,name,prompt,cron,timezone,enabled:true});}}><div className="section-heading">Create a routine</div><label>Owning Bot<select value={botId} onChange={e=>setBotId(e.target.value)}>{bots.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label>Name<input required value={name} onChange={e=>setName(e.target.value)}/></label><label>Task<textarea required value={prompt} onChange={e=>setPrompt(e.target.value)}/></label><div className="form-grid"><label>Schedule (cron)<input required value={cron} onChange={e=>setCron(e.target.value)}/></label><label>Timezone<input required value={timezone} onChange={e=>setTimezone(e.target.value)}/></label></div><button className="primary">Create routine</button></form>;}
function GroupForm({bots,save}:{bots:Bot[];save:(v:any)=>void}){const[title,setTitle]=useState(''),[ids,setIds]=useState<string[]>([]);return <form onSubmit={e=>{e.preventDefault();save({title,botIds:ids});}}><label>Group name<input required value={title} onChange={e=>setTitle(e.target.value)}/></label>{bots.map(b=><label key={b.id} className="checkbox"><input type="checkbox" checked={ids.includes(b.id)} onChange={e=>setIds(old=>e.target.checked?[...old,b.id]:old.filter(x=>x!==b.id))}/>{b.name}</label>)}<button className="primary" disabled={ids.length<2}>Create group</button></form>;}
function RelayForm({save}:{save:(v:any)=>void}){const[endpoint,setEndpoint]=useState(''),[token,setToken]=useState('');return <form onSubmit={e=>{e.preventDefault();save({endpoint,token});setToken('');}}><label>Self-hosted signaling endpoint<input required value={endpoint} onChange={e=>setEndpoint(e.target.value)} placeholder="wss://relay.example.com/ws"/></label><label>Relay provisioning token<input type="password" autoComplete="off" value={token} onChange={e=>setToken(e.target.value)} placeholder="Required for the first host registration"/></label><button className="primary">Connect relay</button></form>;}
if(location.hash==='#remote')startRemote();else createRoot(document.getElementById('root')!).render(<App/>);
